### ISSUE TITLE
write_bytes_helper() errno: 1 'Operation not permitted'

### ISSUE THREAD

**Issue by CyberShadow** [mozilla/rr#1378]
Attempting to record the execution of a program yields the following:

```
ghdaemon@k3:~/GHDaemon$ sudo rr record ./ghdaemon

rr: Warning: Your CPU frequency governor is 'ondemand'.  rr strongly
    recommends that you use the 'performance' governor.  Not using the
    'performance' governor can cause rr to be at least 2x slower
    on laptops.

    On Fedora-based systems, you can enable the 'performance' governor
    by running the following commands:

    $ sudo yum install kernel-tools
    $ sudo cpupower frequency-set -g performance

rr: Saving the execution of `./ghdaemon' to trace directory `/home/ghdaemon/.rr/ghdaemon-3'.
[FATAL /home/vladimir/rr/rr/src/task.cc:2004:write_bytes_helper() errno: 1 'Operation not permitted']
 (task 17775 (rec:17775) at time 1)
 ->  Assertion `nwritten == buf_size' failed to hold. Should have written 2 bytes to 0xe6b1e430, but only wrote -1
Attach to the rr debug server with this command:
  target remote :17775
```

Stack trace for the assertion failure:

```
#0  Task::write_bytes_helper (this=0xbd154e8, addr=..., buf_size=2, buf=0xbd161c0)
    at /home/vladimir/rr/rr/src/task.cc:2004
#1  0x080eaea5 in Task::write_mem<unsigned char> (this=0xbd154e8, child_addr=..., val=0xbd161c0 "]Z", count=2)
    at /home/vladimir/rr/rr/src/task.h:900
#2  0x080e8503 in AutoRemoteSyscalls::restore_state_to (this=0xffffd380, t=0xbd154e8)
    at /home/vladimir/rr/rr/src/AutoRemoteSyscalls.cc:64
#3  0x080e84a8 in AutoRemoteSyscalls::~AutoRemoteSyscalls (this=0xffffd380, __in_chrg=<optimised out>)
    at /home/vladimir/rr/rr/src/AutoRemoteSyscalls.cc:60
#4  0x0816ee5b in Task::open_mem_fd (this=0xbd154e8) at /home/vladimir/rr/rr/src/task.cc:1776
#5  0x08170e20 in Task::spawn (session=..., trace=..., rec_tid=-1) at /home/vladimir/rr/rr/src/task.cc:2211
#6  0x08119e86 in RecordSession::RecordSession (this=0xbd14a48, argv=..., envp=..., cwd=..., bind_to_cpu=5)
    at /home/vladimir/rr/rr/src/RecordSession.cc:838
#7  0x08119d53 in RecordSession::create (argv=..., envp=..., cwd=...) at /home/vladimir/rr/rr/src/RecordSession.cc:828
#8  0x0811584c in record (rr_exe=0xffffe8e4 "/usr/local/bin/rr", argc=1, argv=0xffffe7bc, envp=0xbd13ef0)
    at /home/vladimir/rr/rr/src/recorder.cc:80
#9  0x0811358f in main (argc=1, argv=0xffffe7bc) at /home/vladimir/rr/rr/src/main.cc:607
```

This machine is using a kernel built by the server host, OVH: `3.10.9-xxxx-grs-ipv6-64`
It has grsec, and though this line shows up in the syslog, it doesn't appear to be blocking rr:
```
Nov 24 02:35:31 k3 kernel: grsec: From 178.168.83.51: process /home/vladimir/rr/obj/bin/rr(rr:31884) attached to via ptrace by /home/vladimir/rr/obj/bin/rr[rr:31876] uid/euid:0/0 gid/egid:0/0, parent /bin/bash[bash:31870] uid/euid:0/0 gid/egid:0/0
```

**Comment by CyberShadow** [comment]
I understand. Thank you for your efforts so far.

**Comment by thestinger** [comment]
The grsecurity patch was changed to make it compatible with rr:

    Allow active ptracers access to /proc/pid/maps and /proc/pid/mem for tasks
    they are ptracing.  Also clean up the maps code to avoid duplicate PaX flag
    checks.  Thanks to ekleog for reporting and testing, and Robert O'Callahan
    for collaborating on changes/cleanups to rr to fix support for grsecurity.

https://grsecurity.net/changelog-test.txt

The separate issue of needing runtime code generation can just be dealt with by adding an MPROTECT exception, which is not unexpected.

**Comment by rocallahan** [comment]
Yes, I believe this is fixed now!
