### ISSUE TITLE
Crash when deleting a non-explicit checkpoint

### ISSUE THREAD

**Issue by bgirard** [mozilla/rr#1656]
I'll try and take a look at this, filing now since I'm debugging something else.

```
(rr) checkpoint
Checkpoint 4 at   nsDisplayList::PaintRoot (this=0x7ffede3eaf50, aBuilder=0x7ffede3eb180, aCtx=0x7ffede3eb970, aFlags=1) at /home/bgirard/mozilla-central/tree/layout/base/nsDisplayList.cpp:1565
(rr) delete checkpoint 4
rr: /home/bgirard/rr/src/ReplayTimeline.cc:288: void ReplayTimeline::remove_explicit_checkpoint(const ReplayTimeline::Mark&): Assertion `mark.ptr->checkpoint_refcount > 0' failed.
Traceback (most recent call last):
  File "<string>", line 51, in invoke
  File "<string>", line 60, in rr_cmd
gdb.error: Remote connection closed
Error occurred in Python command: Remote connection closed
```

**Comment by bgirard** [comment]
This was broken by my recent PR to add non explicit checkpoints.

**Comment by bgirard** [comment]
See PR #1657.

I wonder if the 'checkpoint' command should just create non explicit checkpoint. They seem fast enough to me.

**Comment by rocallahan** [comment]
Maybe ... creating explicit checkpoints is pretty necessary for testing, though I guess we could have a separate command for testing. Probably just leave it for now.
