### ISSUE TITLE
Hang during recording

### ISSUE THREAD

**Issue by Keno** [mozilla/rr#1764]
RR hangs during recording of a rather complicated julia test. Stack trace is:
```
#0  0x00007f453f430ed9 in __libc_waitpid (pid=3292, stat_loc=0x7ffc61a1b9e4,
    options=1073741824) at ../sysdeps/unix/sysv/linux/waitpid.c:40
#1  0x00007f45407f36a2 in rr::Task::wait (this=0x1099970,
    interrupt_after_elapsed=0) at /home/kfischer/rr/src/Task.cc:1077
#2  0x00007f45407f09d1 in rr::Task::resume_execution (this=0x1099970,
    how=rr::RESUME_SINGLESTEP, wait_how=rr::RESUME_WAIT,
    tick_period=rr::RESUME_NO_TICKS, sig=11)
    at /home/kfischer/rr/src/Task.cc:848
#3  0x00007f45407343cd in rr::inject_handled_signal (t=0x1099970)
    at /home/kfischer/rr/src/RecordSession.cc:998
#4  0x00007f4540733f07 in rr::RecordSession::signal_state_changed (
    this=0x1064a10, t=0x1099970, step_state=0x7ffc61a1bf50)
    at /home/kfischer/rr/src/RecordSession.cc:1084
#5  0x00007f4540738763 in rr::RecordSession::record_step (this=0x1064a10)
    at /home/kfischer/rr/src/RecordSession.cc:1709
#6  0x00007f454072f715 in rr::record (
    args=std::vector of length 2, capacity 4 = {...}, flags=...)
    at /home/kfischer/rr/src/RecordCommand.cc:296
#7  0x00007f454072ed96 in rr::RecordCommand::run (
    this=0x6091f8 <rr::RecordCommand::singleton>,
    args=std::vector of length 2, capacity 4 = {...})
    at /home/kfischer/rr/src/RecordCommand.cc:363
#8  0x0000000000404ae5 in main (argc=4, argv=0x7ffc61a1c358)
    at /home/kfischer/rr/src/main.cc:270
```
However, the pid it seems to be waiting for is in disk sleep state trying to create a core dump? Not sure what exactly is happening. Core dumps should be disabled on this machine.
```
kfischer2@nanosoldier1:~/julia$ cat /proc/3292/status
Name:	julia
State:	D (disk sleep)
Tgid:	3291
Ngid:	0
Pid:	3292
PPid:	3244
TracerPid:	2347
Uid:	1003	1003	1003	1003
Gid:	1003	1003	1003	1003
FDSize:	1024
Groups:	1003 1095828719
VmPeak:	 9043356 kB
VmSize:	 9033132 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	  169580 kB
VmRSS:	  169580 kB
VmData:	 8788992 kB
VmStk:	       0 kB
VmExe:	       8 kB
VmLib:	  104220 kB
VmPTE:	     676 kB
VmSwap:	       0 kB
Threads:	9
SigQ:	0/256922
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000004226
SigIgn:	0000000000001010
SigCgt:	00000001c0000ae8
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	0000001fffffffff
Seccomp:	2
Cpus_allowed:	10
Cpus_allowed_list:	4
Mems_allowed:	00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	1058
nonvoluntary_ctxt_switches:	3
kfischer2@nanosoldier1:~/julia$ cat /proc/3292/stack
[<ffffffff8121e9b3>] do_coredump+0x343/0xea0
[<ffffffff8107c6e7>] get_signal_to_deliver+0x1c7/0x6f0
[<ffffffff81014418>] do_signal+0x48/0xa10
[<ffffffff81014e49>] do_notify_resume+0x69/0xb0
[<ffffffff81731ee2>] retint_signal+0x48/0x86
[<ffffffffffffffff>] 0xffffffffffffffff
```

**Comment by Keno** [comment]
Also seen on linux 4.7rc7.

**Comment by rocallahan** [comment]
Can you look into what the kernel thinks it's doing there?

**Comment by Keno** [comment]
Yep, I'm on it. So far it seems the kernel and tt are disagreeing on whether or not the user SEGV handler is being called. The kernel thinks it shouldn't be (haven't figured out why), so it tries to do a coredump and tries to kill all other threads (and wait for them to be done), but since they are in ptrace stops the kernel ends up waiting for a really long time.

**Comment by rocallahan** [comment]
> So far it seems the kernel and rr are disagreeing on whether or not the user SEGV handler is being called.

OK, so that'll be the root cause then.

**Comment by Keno** [comment]
Yep, I'm trying
```
diff --git a/src/RecordSession.cc b/src/RecordSession.cc
index 91e5a86..850646e 100644
--- a/src/RecordSession.cc
+++ b/src/RecordSession.cc
@@ -996,6 +996,7 @@ static bool inject_handled_signal(RecordTask* t) {

   int sig = t->ev().Signal().siginfo.si_signo;
   t->resume_execution(RESUME_SINGLESTEP, RESUME_WAIT, RESUME_NO_TICKS, sig);
+  t->set_sig_blocked(sig);

   // It's been observed that when tasks enter
   // sighandlers, the singlestep operation above
```
to see if that fixes it

**Comment by Keno** [comment]
Yes, seems to have worked. Will put together PR/test case.

**Comment by Keno** [comment]
Hmm, unfortunately my testcase appears to be triggering a different hang :(. Here's what I was trying:
```
#include "rrutil.h"

static void fault_handler(__attribute__((unused)) int sig,
                          __attribute__((unused)) siginfo_t* si,
                          __attribute__((unused)) void* context) {
    raise(SIGSEGV);
}

int main(void) {
  pid_t child;
  int status;

  if ((child = fork()) == 0) {
    struct sigaction act;
    act.sa_sigaction = fault_handler;
    act.sa_flags = SA_SIGINFO | SA_NODEFER;
    sigemptyset(&act.sa_mask);
    sigaction(SIGSEGV, &act, NULL);
    raise(SIGSEGV);
    test_assert(0 && "Should not reach here");
    return 0;
  }

  test_assert(child == wait(&status));
  test_assert(WIFSIGNALED(status) && WTERMSIG(status) == SIGSEGV);
  atomic_puts("EXIT-SUCCESS");
  return 0;
}
```
Will investigate this new hang as well.

**Comment by Keno** [comment]
Even worse that test case was passing without my patch, so I guess I've created an anti-testcase. sigh. Will keep looking.

**Comment by Keno** [comment]
Ah, I of course mindlessly set SA_NODEFER, which is precisely that case that I'm not interested in here. Hold on, PR incoming.

**Comment by Keno** [comment]
Ok, I have a working patch/test case for this, but I've found a couple more case that also need fixing in the same general vicinity of this code. Will have a comprehensive PR tomorrow.
