### ISSUE TITLE
Assertion failure in Linux 4.7.2

### ISSUE THREAD

**Issue by yan12125** [mozilla/rr#1779]
I'm trying rr with mozilla-central. Here's the error I got:
```
$ ./mach run --debugger=rr
0:00.13 /home/yen/tmp/rr/bin/rr /home/yen/tmp/mozilla-central-win/obj-x86_64-pc-linux-gnu/dist/bin/firefox -no-remote -profile /home/yen/tmp/mozilla-central-win/obj-x86_64-pc-linux-gnu/tmp/scratch_user
rr: Saving execution to trace directory `/home/yen/.local/share/rr/firefox-1'.
[FATAL /home/yen/tmp/rr/src/record_syscall.cc:3882:rec_process_syscall_arch() errno: SUCCESS] 
 (task 10146 (rec:10146) at time 2575)
 -> Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected EINVAL for 'madvise' but got result 0 (errno SUCCESS); unknown madvise(8)
Launch gdb with 
  gdb '-l' '-1' '-ex' 'target extended-remote :10146' /home/yen/tmp/mozilla-central-win/obj-x86_64-pc-linux-gnu/dist/bin/firefox
```
I have tried w/o sudo. The error message is the same.

Environment:
* Arch Linux x86_64
* Linux kernel 4.7.2
* GCC 6.1.1 (actually GCC's commit c8454ab1. Arch constantly bumps GCC to the latest commit)

**Comment by khuey** [comment]
This is MADV_FREE, which is new in the 4.5 kernel.

**Comment by yan12125** [comment]
Thanks for the super fast reply, but sorry I didn't get it. Is it a kernel bug or rr's issue?

**Comment by rocallahan** [comment]
rr issue. I'll take it.

**Comment by rocallahan** [comment]
This is actually quite nasty. After a successful `MADV_FREE`, the kernel will nondeterministically zero the page if it's not touched again :-(. We can't handle that.

I can see a few alternatives:
1) Reject `MADV_FREE` with `EINVAL`.
2) Pretend `MADV_FREE` succeeded but don't pass it on to the kernel.
3) Turn `MADV_FREE` into `MADV_DONTNEED` which zeroes the page immediately.
4) Emulate `MADV_FREE` somehow by monitoring mem usage and synchronously doing it at some point if necessary. This is pretty hard though since we need to cancel `MADV_FREE` if there's a write to the page.

**Comment by rocallahan** [comment]
I think for now I'll go with #1. That should be fine for now since it's a very new kernel feature.

**Comment by khuey** [comment]
2 will lead to leaks in the tracee.

**Comment by rocallahan** [comment]
Only if it leaks address space already.

**Comment by yan12125** [comment]
Thanks for the fix. Though I got a different error now:
```
0:00.13 /home/yen/tmp/rr/bin/rr /home/yen/tmp/mozilla-central-win/obj-x86_64-pc-linux-gnu/dist/bin/firefox -no-remote -profile /home/yen/tmp/mozilla-central-win/obj-x86_64-pc-linux-gnu/tmp/scratch_user
rr: Saving execution to trace directory `/root/.local/share/rr/firefox-1'.
[FATAL /home/yen/tmp/rr/src/record_syscall.cc:4008:rec_process_syscall_arch() errno: SUCCESS] 
 (task 7893 (rec:7893) at time 29749)
 -> Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected EINVAL for 'futex' but got result -1 (errno EPERM); unknown futex(0x7)
Launch gdb with 
  gdb '-l' '-1' '-ex' 'target extended-remote :7893' /home/yen/tmp/mozilla-central-win/obj-x86_64-pc-linux-gnu/dist/bin/plugin-container
```

**Comment by rocallahan** [comment]
Can you connect the emergency debugger with the command after "Launch gdb with", and do "info registers" and "where"?

**Comment by yan12125** [comment]
Here it is:
```
(gdb) info registers 
rax            0xffffffffffffffff	-1
rbx            0x7fa466b67bb0	140344074599344
rcx            0xffffffffffffffff	-1
rdx            0x0	0
rsi            0x7	7
rdi            0x7fff75a3debc	140735167061692
rbp            0x7fff75a3dee0	0x7fff75a3dee0
rsp            0x7fff75a3dea0	0x7fff75a3dea0
r8             0x0	0
r9             0x7fa466b67004	140344074596356
r10            0x0	0
r11            0x246	582
r12            0x7fa466b67bb0	140344074599344
r13            0x7fa484456438	140344570504248
r14            0x7fa46a4fcf10	140344134979344
r15            0x0	0
rip            0x7fa48448f3fe	0x7fa48448f3fe <pthread_mutex_init+350>
eflags         0x246	[ PF ZF IF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
(gdb) where 
#0  0x00007fa48448f3fe in pthread_mutex_init () from /usr/lib/libpthread.so.0
#1  0x00007fa468680ea5 in pa_mutex_new (recursive=recursive@entry=true, 
    inherit_priority=inherit_priority@entry=true) at pulsecore/mutex-posix.c:65
#2  0x00007fa4688e31bf in pa_threaded_mainloop_new () at pulse/thread-mainloop.c:117
#3  0x00007fa4822117cf in pulse_init (
    context=context@entry=0x7fa484456438 <mozilla::(anonymous namespace)::sCubebContext>, 
    context_name=context_name@entry=0x7fa46a4fcf10 "Nightly")
    at /home/yen/tmp/mozilla-central-win/media/libcubeb/src/cubeb_pulse.c:526
#4  0x00007fa48220eb61 in cubeb_init (
    context=context@entry=0x7fa484456438 <mozilla::(anonymous namespace)::sCubebContext>, 
    context_name=0x7fa46a4fcf10 "Nightly") at /home/yen/tmp/mozilla-central-win/media/libcubeb/src/cubeb.c:164
#5  0x00007fa48164d66a in mozilla::CubebUtils::GetCubebContextUnlocked ()
    at /home/yen/tmp/mozilla-central-win/dom/media/CubebUtils.cpp:177
#6  0x00007fa48164f191 in mozilla::CubebUtils::GetCubebContext ()
    at /home/yen/tmp/mozilla-central-win/dom/media/CubebUtils.cpp:123
#7  0x00007fa4818b0bbc in mozilla::dom::ContentChild::RecvSetProcessSandbox (this=<optimized out>, aBroker=...)
    at /home/yen/tmp/mozilla-central-win/dom/ipc/ContentChild.cpp:1359
#8  0x00007fa480ab2cb2 in mozilla::dom::PContentChild::OnMessageReceived (this=0x7fa472b81020, msg__=...)
    at /home/yen/tmp/mozilla-central-win/obj-x86_64-pc-linux-gnu/ipc/ipdl/PContentChild.cpp:7847
#9  0x00007fa4807dcb0b in mozilla::ipc::MessageChannel::DispatchAsyncMessage (this=0x7fa472b81088, aMsg=...)
    at /home/yen/tmp/mozilla-central-win/ipc/glue/MessageChannel.cpp:1662
#10 0x00007fa4807e2c07 in mozilla::ipc::MessageChannel::DispatchMessage(IPC::Message&&) (
    this=this@entry=0x7fa472b81088, 
    aMsg=aMsg@entry=<unknown type in /home/yen/tmp/mozilla-central-win/obj-x86_64-pc-linux-gnu/dist/bin/libxul.so, CU 0x25c4ff8, DIE 0x2635a1f>) at /home/yen/tmp/mozilla-central-win/ipc/glue/MessageChannel.cpp:1600
#11 0x00007fa4807e3d0c in mozilla::ipc::MessageChannel::OnMaybeDequeueOne (this=0x7fa472b81088)
    at /home/yen/tmp/mozilla-central-win/ipc/glue/MessageChannel.cpp:1567
#12 0x00007fa4807e4f8e in mozilla::detail::RunnableMethodArguments<>::applyImpl<mozilla::ipc::MessageChannel, bool (mozilla::ipc::MessageChannel::*)()>(mozilla::ipc::MessageChannel*, bool (mozilla::ipc::MessageChannel::*)(),---Type <return> to continue, or q <return> to quit---
 mozilla::Tuple<>&, mozilla::IndexSequence<>) (args=..., m=<optimized out>, o=<optimized out>)
    at /home/yen/tmp/mozilla-central-win/obj-x86_64-pc-linux-gnu/dist/include/nsThreadUtils.h:729
#13 mozilla::detail::RunnableMethodArguments<>::apply<mozilla::ipc::MessageChannel, bool (mozilla::ipc::MessageChannel::*)()>(mozilla::ipc::MessageChannel*, bool (mozilla::ipc::MessageChannel::*)()) (this=<optimized out>, 
    m=<optimized out>, o=<optimized out>)
    at /home/yen/tmp/mozilla-central-win/obj-x86_64-pc-linux-gnu/dist/include/nsThreadUtils.h:736
#14 mozilla::detail::RunnableMethodImpl<bool (mozilla::ipc::MessageChannel::*)(), false, true>::Run (
    this=<optimized out>)
    at /home/yen/tmp/mozilla-central-win/obj-x86_64-pc-linux-gnu/dist/include/nsThreadUtils.h:764
#15 0x00007fa4807e4cb1 in mozilla::ipc::MessageChannel::RefCountedTask::Run (this=<optimized out>)
    at /home/yen/tmp/mozilla-central-win/obj-x86_64-pc-linux-gnu/dist/include/mozilla/ipc/MessageChannel.h:545
#16 mozilla::ipc::MessageChannel::DequeueTask::Run (this=<optimized out>)
    at /home/yen/tmp/mozilla-central-win/obj-x86_64-pc-linux-gnu/dist/include/mozilla/ipc/MessageChannel.h:564
#17 0x00007fa4804a6913 in nsThread::ProcessNextEvent (this=0x7fa4709aa0e0, aMayWait=<optimized out>, 
    aResult=0x7fff75a3e3ef) at /home/yen/tmp/mozilla-central-win/xpcom/threads/nsThread.cpp:1058
#18 0x00007fa4804c18e2 in NS_ProcessNextEvent (aThread=<optimized out>, aMayWait=<optimized out>)
    at /home/yen/tmp/mozilla-central-win/xpcom/glue/nsThreadUtils.cpp:290
#19 0x00007fa4807da158 in mozilla::ipc::MessagePump::Run (this=0x7fa472b83290, aDelegate=0x7fff75a3e5d0)
    at /home/yen/tmp/mozilla-central-win/ipc/glue/MessagePump.cpp:96
#20 0x00007fa4807ab7aa in MessageLoop::RunHandler (this=<optimized out>)
    at /home/yen/tmp/mozilla-central-win/ipc/chromium/src/base/message_loop.cc:225
#21 MessageLoop::Run (this=<optimized out>)
    at /home/yen/tmp/mozilla-central-win/ipc/chromium/src/base/message_loop.cc:205
#22 0x00007fa481a162b6 in nsBaseAppShell::Run (this=0x7fa468cdce40)
    at /home/yen/tmp/mozilla-central-win/widget/nsBaseAppShell.cpp:156
#23 0x00007fa4820a2a1d in XRE_RunAppShell ()
    at /home/yen/tmp/mozilla-central-win/toolkit/xre/nsEmbedFunctions.cpp:846
#24 0x00007fa4807ab7aa in MessageLoop::RunHandler (this=0x7fff75a3e5d0)
    at /home/yen/tmp/mozilla-central-win/ipc/chromium/src/base/message_loop.cc:225
---Type <return> to continue, or q <return> to quit---
#25 MessageLoop::Run (this=this@entry=0x7fff75a3e5d0)
    at /home/yen/tmp/mozilla-central-win/ipc/chromium/src/base/message_loop.cc:205
#26 0x00007fa4820a308f in XRE_InitChildProcess (aArgc=3, aArgc@entry=5, aArgv=aArgv@entry=0x7fff75a3e8c8, 
    aChildData=aChildData@entry=0x7fff75a3e7c0)
    at /home/yen/tmp/mozilla-central-win/toolkit/xre/nsEmbedFunctions.cpp:676
#27 0x0000000000408c96 in content_process_main (argc=6, argv=0x7fff75a3e8c8)
    at /home/yen/tmp/mozilla-central-win/ipc/app/../contentproc/plugin-container.cpp:197
#28 0x00007fa47e9cf291 in __libc_start_main () from /usr/lib/libc.so.6
#29 0x000000000040883a in _start ()
```

**Comment by rocallahan** [comment]
Pulseaudio started using priority-inheriting futexes which rr doesn't currently support. We need to fix that. Look into it tomorrow.

**Comment by yan12125** [comment]
I don't even know how to express my gratitude :) Now I can debug my Firefox!

**Comment by rocallahan** [comment]
Just spread the word about rr :-)

**Comment by yan12125** [comment]
Of course. It's excellent!
