### ISSUE TITLE
rr causes gdb to crash due to double free

### ISSUE THREAD

**Issue by nagisa** [mozilla/rr#1939]
rr used to work before, but doesn’t anymore for some reason:

```
$ rr record echo "banana"

rr: Warning: Your CPU frequency governor is 'powersave'.  rr strongly
    recommends that you use the 'performance' governor.  Not using the
    'performance' governor can cause rr to be at least 2x slower
    on laptops.

    On Fedora-based systems, you can enable the 'performance' governor
    by running the following commands:

    $ sudo dnf install kernel-tools
    $ sudo cpupower frequency-set -g performance

rr: Saving execution to trace directory `/home/nagisa/local/share/rr/echo-0'.
banana

$ rr replay /home/nagisa/local/share/rr/echo-0/

rr: Warning: Your CPU frequency governor is 'powersave'.  rr strongly
    recommends that you use the 'performance' governor.  Not using the
    'performance' governor can cause rr to be at least 2x slower
    on laptops.

    On Fedora-based systems, you can enable the 'performance' governor
    by running the following commands:

    $ sudo dnf install kernel-tools
    $ sudo cpupower frequency-set -g performance

GNU gdb (GDB) 7.12
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/echo...(no debugging symbols found)...done.
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
>>> *** Error in `gdb': double free or corruption (out): 0x00007fad195a00f0 ***
======= Backtrace: =========
/usr/lib/libc.so.6(+0x70c4b)[0x7fad177bec4b]
/usr/lib/libc.so.6(+0x76fe6)[0x7fad177c4fe6]
/usr/lib/libc.so.6(+0x777de)[0x7fad177c57de]
/usr/lib/libpython3.6m.so.1.0(PyOS_Readline+0x138)[0x7fad180252e3]
/usr/lib/libpython3.6m.so.1.0(+0xe96a7)[0x7fad180256a7]
/usr/lib/libpython3.6m.so.1.0(PyTokenizer_Get+0x9)[0x7fad18100b89]
/usr/lib/libpython3.6m.so.1.0(PyParser_ParseFileObject+0xf3)[0x7fad1815d103]
/usr/lib/libpython3.6m.so.1.0(PyParser_ASTFromFileObject+0x7e)[0x7fad1812d86e]
/usr/lib/libpython3.6m.so.1.0(PyRun_InteractiveOneObject+0x1f8)[0x7fad17fcc1a2]
/usr/lib/libpython3.6m.so.1.0(PyRun_InteractiveLoopFlags+0xd3)[0x7fad17fcc3bd]
gdb[0x4b239a]
gdb[0x4917c3]
gdb[0x65e763]
gdb[0x59aafc]
gdb[0x65f068]
gdb[0x4939ad]
gdb[0x495de5]
gdb[0x593338]
gdb[0x5943de]
gdb[0x40eb25]
/usr/lib/libc.so.6(__libc_start_main+0xf1)[0x7fad1776e291]
gdb[0x4102fa]
======= Memory map: ========
00400000-00a3b000 r-xp 00000000 08:02 362777                             /usr/bin/gdb
00c3a000-00c3c000 r--p 0063a000 08:02 362777                             /usr/bin/gdb
00c3c000-00c54000 rw-p 0063c000 08:02 362777                             /usr/bin/gdb
00c54000-00c7d000 rw-p 00000000 00:00 0 
0155c000-01d7d000 rw-p 00000000 00:00 0                                  [heap]
7fad0c000000-7fad0c021000 rw-p 00000000 00:00 0 
7fad0c021000-7fad10000000 ---p 00000000 00:00 0 
7fad12034000-7fad1204a000 r-xp 00000000 08:02 391486                     /usr/lib/libgcc_s.so.1
7fad1204a000-7fad12249000 ---p 00016000 08:02 391486                     /usr/lib/libgcc_s.so.1
7fad12249000-7fad1224a000 r--p 00015000 08:02 391486                     /usr/lib/libgcc_s.so.1
7fad1224a000-7fad1224b000 rw-p 00016000 08:02 391486                     /usr/lib/libgcc_s.so.1
7fad1224b000-7fad122d4000 rw-p 00000000 00:00 0 
7fad12314000-7fad12414000 rw-p 00000000 00:00 0 
7fad12414000-7fad12428000 r--p 00000000 08:02 529391                     /usr/lib/guile/2.0/ccache/ice-9/format.go
7fad12428000-7fad1243d000 r--p 00000000 08:02 529406                     /usr/lib/guile/2.0/ccache/ice-9/vlist.go
7fad1243d000-7fad1244e000 r--p 00000000 08:02 657866                     /usr/lib/guile/2.0/ccache/language/scheme/decompile-tree-il.go
7fad1244e000-7fad12450000 r--p 00000000 08:02 689615                     /usr/lib/guile/2.0/ccache/srfi/srfi-11.go
7fad12450000-7fad12463000 r--p 00000000 08:02 657865                     /usr/lib/guile/2.0/ccache/language/tree-il.go
7fad12463000-7fad12464000 r--p 00000000 08:02 657867                     /usr/lib/guile/2.0/ccache/language/scheme/compile-tree-il.go
7fad12464000-7fad12465000 r--p 00000000 08:02 657868                     /usr/lib/guile/2.0/ccache/language/scheme/spec.go
7fad12465000-7fad12467000 r--p 00000000 08:02 689608                     /usr/lib/guile/2.0/ccache/srfi/srfi-26.go
7fad12467000-7fad1246b000 r--p 00000000 08:02 758440                     /usr/lib/guile/2.0/ccache/srfi/srfi-9/gnu.go
7fad1246b000-7fad1246e000 r--p 00000000 08:02 561951                     /usr/lib/guile/2.0/ccache/system/foreign.go
7fad1246e000-7fad12470000 r--p 00000000 08:02 624437                     /usr/lib/guile/2.0/ccache/system/base/target.go
7fad12470000-7fad12471000 r--p 00000000 08:02 758402                     /usr/lib/guile/2.0/ccache/system/vm/objcode.go
7fad12471000-7fad12472000 r--p 00000000 08:02 758403                     /usr/lib/guile/2.0/ccache/system/vm/instruction.go
7fad12472000-7fad12476000 r--p 00000000 08:02 758401                     /usr/lib/guile/2.0/ccache/system/vm/program.go
7fad12476000-7fad12477000 r--p 00000000 08:02 529370                     /usr/lib/guile/2.0/ccache/ice-9/receive.go
7fad12477000-7fad1247a000 r--p 00000000 08:02 624443                     /usr/lib/guile/2.0/ccache/system/base/pmatch.go
7fad1247a000-7fad12480000 r--p 00000000 08:02 529377                     /usr/lib/guile/2.0/ccache/ice-9/optargs.go
7fad12480000-7fad12482000 r--p 00000000 08:02 529369                     /usr/lib/guile/2.0/ccache/ice-9/regex.go
7fad12482000-7fad1249a000 r--p 00000000 08:02 529381                     /usr/lib/guile/2.0/ccache/ice-9/match.go
7fad1249a000-7fad1249c000 r--p 00000000 08:02 622652                     /usr/lib/guile/2.0/ccache/system/base/ck.go
7fad1249c000-7fad124a4000 r--p 00000000 08:02 689617                     /usr/lib/guile/2.0/ccache/srfi/srfi-9.go
7fad124a4000-7fad124af000 r--p 00000000 08:02 689622                     /usr/lib/guile/2.0/ccache/srfi/srfi-1.go
7fad124af000-7fad124b7000 r--p 00000000 08:02 624438                     /usr/lib/guile/2.0/ccache/system/base/message.go
7fad124b7000-7fad124bc000 r--p 00000000 08:02 624442                     /usr/lib/guile/2.0/ccache/system/base/syntax.go
7fad124bc000-7fad124c0000 r--p 00000000 08:02 624441                     /usr/lib/guile/2.0/ccache/system/base/compile.go
7fad124c0000-7fad124cd000 r--p 00000000 08:02 529403                     /usr/lib/guile/2.0/ccache/ice-9/deprecated.go
7fad124cd000-7fad1250f000 r--p 00000000 08:02 529407                     /usr/lib/guile/2.0/ccache/ice-9/boot-9.go
7fad1250f000-7fad12511000 r-xp 00000000 08:02 388199                     /usr/lib/gconv/ISO8859-1.so
7fad12511000-7fad12710000 ---p 00002000 08:02 388199                     /usr/lib/gconv/ISO8859-1.so
7fad12710000-7fad12711000 r--p 00001000 08:02 388199                     /usr/lib/gconv/ISO8859-1.so
7fad12711000-7fad12712000 rw-p 00002000 08:02 388199                     /usr/lib/gconv/ISO8859-1.so
7fad12712000-7fad12713000 ---p 00000000 00:00 0 
7fad12713000-7fad12f13000 rw-p 00000000 00:00 0 
7fad12f13000-7fad12f14000 ---p 00000000 00:00 0 
7fad12f14000-7fad13714000 rw-p 00000000 00:00 0 
7fad13714000-7fad13715000 ---p 00000000 00:00 0 
7fad13715000-7fad13f15000 rw-p 00000000 00:00 0 
7fad13f15000-7fad13f16000 ---p 00000000 00:00 0 
7fad13f16000-7fad14716000 rw-p 00000000 00:00 0 
7fad14716000-7fad14717000 ---p 00000000 00:00 0 
7fad14717000-7fad14f17000 rw-p 00000000 00:00 0 
7fad14f17000-7fad14f18000 ---p 00000000 00:00 0 
7fad14f18000-7fad15718000 rw-p 00000000 00:00 0 
7fad15718000-7fad15719000 ---p 00000000 00:00 0 
7fad15719000-7fad15f59000 rw-p 00000000 00:00 0 
7fad15f59000-7fad15f5c000 r-xp 00000000 08:02 449769                     /usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so
7fad15f5c000-7fad1615b000 ---p 00003000 08:02 449769                     /usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so
7fad1615b000-7fad1615c000 r--p 00002000 08:02 449769                     /usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so
7fad1615c000-7fad1615e000 rw-p 00003000 08:02 449769                     /usr/lib/python3.6/lib-dynload/_heapq.cpython-36m-x86_64-linux-gnu.so
7fad1615e000-7fad161de000 rw-p 00000000 00:00 0 
7fad161de000-7fad1648f000 r--p 00000000 08:02 404756                     /usr/lib/locale/locale-archive
7fad1648f000-7fad16490000 r-xp 00000000 08:02 383765                     /usr/lib/libatomic_ops.so.1.0.3
7fad16490000-7fad16690000 ---p 00001000 08:02 383765                     /usr/lib/libatomic_ops.so.1.0.3
7fad16690000-7fad16691000 r--p 00001000 08:02 383765                     /usr/lib/libatomic_ops.so.1.0.3
7fad16691000-7fad16692000 rw-p 00002000 08:02 383765                     /usr/lib/libatomic_ops.so.1.0.3
7fad16692000-7fad16694000 r-xp 00000000 08:02 363012                     /usr/lib/libutil-2.24.so
7fad16694000-7fad16893000 ---p 00002000 08:02 363012                     /usr/lib/libutil-2.24.so
7fad16893000-7fad16894000 r--p 00001000 08:02 363012                     /usr/lib/libutil-2.24.so
7fad16894000-7fad16895000 rw-p 00002000 08:02 363012                     /usr/lib/libutil-2.24.so
7fad16895000-7fad1689d000 r-xp 00000000 08:02 362988                     /usr/lib/libcrypt-2.24.so
7fad1689d000-7fad16a9d000 ---p 00008000 08:02 362988                     /usr/lib/libcrypt-2.24.so
7fad16a9d000-7fad16a9e000 r--p 00008000 08:02 362988                     /usr/lib/libcrypt-2.24.so
7fad16a9e000-7fad16a9f000 rw-p 00009000 08:02 362988                     /usr/lib/libcrypt-2.24.so
7fad16a9f000-7fad16acd000 rw-p 00000000 00:00 0 
7fad16acd000-7fad16ad6000 r-xp 00000000 08:02 380846                     /usr/lib/libltdl.so.7.3.1
7fad16ad6000-7fad16cd5000 ---p 00009000 08:02 380846                     /usr/lib/libltdl.so.7.3.1
7fad16cd5000-7fad16cd6000 r--p 00008000 08:02 380846                     /usr/lib/libltdl.so.7.3.1
7fad16cd6000-7fad16cd7000 rw-p 00009000 08:02 380846                     /usr/lib/libltdl.so.7.3.1
7fad16cd7000-7fad16d69000 r-xp 00000000 08:02 382947                     /usr/lib/libgmp.so.10.3.2
7fad16d69000-7fad16f68000 ---p 00092000 08:02 382947                     /usr/lib/libgmp.so.10.3.2
7fad16f68000-7fad16f69000 r--p 00091000 08:02 382947                     /usr/lib/libgmp.so.10.3.2
7fad16f69000-7fad16f6a000 rw-p 00092000 08:02 382947                     /usr/lib/libgmp.so.10.3.2
7fad16f6a000-7fad170d6000 r-xp 00000000 08:02 368850                     /usr/lib/libunistring.so.2.0.0
7fad170d6000-7fad172d6000 ---p 0016c000 08:02 368850                     /usr/lib/libunistring.so.2.0.0
7fad172d6000-7fad172d9000 r--p 0016c000 08:02 368850                     /usr/lib/libunistring.so.2.0.0
7fad172d9000-7fad172da000 rw-p 0016f000 08:02 368850                     /usr/lib/libunistring.so.2.0.0
7fad172da000-7fad172db000 rw-p 00000000 00:00 0 
7fad172db000-7fad172e2000 r-xp 00000000 08:02 388758                     /usr/lib/libffi.so.6.0.4
7fad172e2000-7fad174e2000 ---p 00007000 08:02 388758                     /usr/lib/libffi.so.6.0.4
7fad174e2000-7fad174e3000 r--p 00007000 08:02 388758                     /usr/lib/libffi.so.6.0.4
7fad174e3000-7fad174e4000 rw-p 00008000 08:02 388758                     /usr/lib/libffi.so.6.0.4
7fad174e4000-7fad1750b000 r-xp 00000000 08:02 383767                     /usr/lib/libgc.so.1.0.3
7fad1750b000-7fad1770a000 ---p 00027000 08:02 383767                     /usr/lib/libgc.so.1.0.3
7fad1770a000-7fad1770b000 r--p 00026000 08:02 383767                     /usr/lib/libgc.so.1.0.3
7fad1770b000-7fad1770c000 rw-p 00027000 08:02 383767                     /usr/lib/libgc.so.1.0.3
7fad1770c000-7fad1774e000 rw-p 00000000 00:00 0 
7fad1774e000-7fad178e3000 r-xp 00000000 08:02 362875                     /usr/lib/libc-2.24.so
7fad178e3000-7fad17ae2000 ---p 00195000 08:02 362875                     /usr/lib/libc-2.24.so
7fad17ae2000-7fad17ae6000 r--p 00194000 08:02 362875                     /usr/lib/libc-2.24.so
7fad17ae6000-7fad17ae8000 rw-p 00198000 08:02 362875                     /usr/lib/libc-2.24.so
7fad17ae8000-7fad17aec000 rw-p 00000000 00:00 0 
7fad17aec000-7fad17b11000 r-xp 00000000 08:02 367812                     /usr/lib/liblzma.so.5.2.3
7fad17b11000-7fad17d10000 ---p 00025000 08:02 367812                     /usr/lib/liblzma.so.5.2.3
7fad17d10000-7fad17d11000 r--p 00024000 08:02 367812                     /usr/lib/liblzma.so.5.2.3
7fad17d11000-7fad17d12000 rw-p 00025000 08:02 367812                     /usr/lib/liblzma.so.5.2.3
7fad17d12000-7fad17d39000 r-xp 00000000 08:02 362984                     /usr/lib/libexpat.so.1.6.2
7fad17d39000-7fad17f39000 ---p 00027000 08:02 362984                     /usr/lib/libexpat.so.1.6.2
7fad17f39000-7fad17f3b000 r--p 00027000 08:02 362984                     /usr/lib/libexpat.so.1.6.2
7fad17f3b000-7fad17f3c000 rw-p 00029000 08:02 362984                     /usr/lib/libexpat.so.1.6.2
7fad17f3c000-7fad18203000 r-xp 00000000 08:02 375734                     /usr/lib/libpython3.6m.so.1.0
7fad18203000-7fad18402000 ---p 002c7000 08:02 375734                     /usr/lib/libpython3.6m.so.1.0
7fad18402000-7fad18405000 r--p 002c6000 08:02 375734                     /usr/lib/libpython3.6m.so.1.0
7fad18405000-7fad1846b000 rw-p 002c9000 08:02 375734                     /usr/lib/libpython3.6m.so.1.0
7fad1846b000-7fad1849c000 rw-p 00000000 00:00 0 
7fad1849c000-7fad1859f000 r-xp 00000000 08:02 363006                     /usr/lib/libm-2.24.so
7fad1859f000-7fad1879e000 ---p 00103000 08:02 363006                     /usr/lib/libm-2.24.so
7fad1879e000-7fad1879f000 r--p 00102000 08:02 363006                     /usr/lib/libm-2.24.so
7fad1879f000-7fad187a0000 rw-p 00103000 08:02 363006                     /usr/lib/libm-2.24.so
7fad187a0000-7fad187b8000 r-xp 00000000 08:02 362836                     /usr/lib/libpthread-2.24.so
7fad187b8000-7fad189b7000 ---p 00018000 08:02 362836                     /usr/lib/libpthread-2.24.so
7fad189b7000-7fad189b8000 r--p 00017000 08:02 362836                     /usr/lib/libpthread-2.24.so
7fad189b8000-7fad189b9000 rw-p 00018000 08:02 362836                     /usr/lib/libpthread-2.24.so
7fad189b9000-7fad189bd000 rw-p 00000000 00:00 0 
7fad189bd000-7fad18b0e000 r-xp 00000000 08:02 383785                     /usr/lib/libguile-2.0.so.22.8.1
7fad18b0e000-7fad18d0d000 ---p 00151000 08:02 383785                     /usr/lib/libguile-2.0.so.22.8.1
7fad18d0d000-7fad18d1f000 r--p 00150000 08:02 383785                     /usr/lib/libguile-2.0.so.22.8.1
7fad18d1f000-7fad18d3e000 rw-p 00162000 08:02 383785                     /usr/lib/libguile-2.0.so.22.8.1
7fad18d3e000-7fad18d4b000 rw-p 00000000 00:00 0 
7fad18d4b000-7fad18db2000 r-xp 00000000 08:02 364024                     /usr/lib/libncursesw.so.6.0
7fad18db2000-7fad18fb1000 ---p 00067000 08:02 364024                     /usr/lib/libncursesw.so.6.0
7fad18fb1000-7fad18fb5000 r--p 00066000 08:02 364024                     /usr/lib/libncursesw.so.6.0
7fad18fb5000-7fad18fb7000 rw-p 0006a000 08:02 364024                     /usr/lib/libncursesw.so.6.0
7fad18fb7000-7fad18fb9000 r-xp 00000000 08:02 363005                     /usr/lib/libdl-2.24.so
7fad18fb9000-7fad191b9000 ---p 00002000 08:02 363005                     /usr/lib/libdl-2.24.so
7fad191b9000-7fad191ba000 r--p 00002000 08:02 363005                     /usr/lib/libdl-2.24.so
7fad191ba000-7fad191bb000 rw-p 00003000 08:02 363005                     /usr/lib/libdl-2.24.so
7fad191bb000-7fad191ff000 r-xp 00000000 08:02 364060                     /usr/lib/libreadline.so.7.0
7fad191ff000-7fad193ff000 ---p 00044000 08:02 364060                     /usr/lib/libreadline.so.7.0
7fad193ff000-7fad19401000 r--p 00044000 08:02 364060                     /usr/lib/libreadline.so.7.0
7fad19401000-7fad19407000 rw-p 00046000 08:02 364060                     /usr/lib/libreadline.so.7.0
7fad19407000-7fad19409000 rw-p 00000000 00:00 0 
7fad19409000-7fad1942c000 r-xp 00000000 08:02 362874                     /usr/lib/ld-2.24.so
7fad1942c000-7fad1942d000 r--p 00000000 08:02 758397                     /usr/lib/guile/2.0/ccache/system/vm/vm.go
7fad1942d000-7fad1942f000 r--p 00000000 08:02 624440                     /usr/lib/guile/2.0/ccache/system/base/language.go
7fad1942f000-7fad19430000 r--p 00000000 08:02 529393                     /usr/lib/guile/2.0/ccache/ice-9/eval-string.go
7fad19430000-7fad19435000 r--p 00000000 08:02 754190                     /usr/share/gdb/guile/gdb.go
7fad19435000-7fad19467000 r--p 00000000 08:02 529408                     /usr/lib/guile/2.0/ccache/ice-9/psyntax-pp.go
7fad19467000-7fad195f2000 rw-p 00000000 00:00 0 
7fad195f2000-7fad195f3000 r--p 00000000 08:02 723696                     /usr/lib/guile/2.0/ccache/rnrs/bytevectors.go
7fad195f3000-7fad195f9000 r--p 00000000 08:02 689620                     /usr/lib/guile/2.0/ccache/srfi/srfi-4.go
7fad195f9000-7fad195fc000 r--p 00000000 08:02 529380                     /usr/lib/guile/2.0/ccache/ice-9/networking.go
7fad195fc000-7fad195fe000 r--p 00000000 08:02 529373                     /usr/lib/guile/2.0/ccache/ice-9/posix.go
7fad195fe000-7fad19601000 r--p 00000000 08:02 529405                     /usr/lib/guile/2.0/ccache/ice-9/r4rs.go
7fad19601000-7fad19605000 r--p 00000000 08:02 529313                     /usr/lib/guile/2.0/ccache/ice-9/eval.go
7fad19629000-7fad1962a000 rw-p 00000000 00:00 0 
7fad1962a000-7fad1962b000 r--p 00000000 08:02 393274                     /usr/share/locale/en_GB/LC_MESSAGES/libc.mo
7fad1962b000-7fad1962c000 r--p 00022000 08:02 362874                     /usr/lib/ld-2.24.so
7fad1962c000-7fad1962d000 rw-p 00023000 08:02 362874                     /usr/lib/ld-2.24.so
7fad1962d000-7fad1962e000 rw-p 00000000 00:00 0 
7fff90a28000-7fff90a49000 rw-p 00000000 00:00 0                          [stack]
7fff90aa2000-7fff90aa4000 r--p 00000000 00:00 0                          [vvar]
7fff90aa4000-7fff90aa6000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
fish: Job 1, “rr replay /home/nagisa/local/sh…” terminated by signal SIGABRT (Abort)
```

```
rr version 4.4.0
GNU gdb (GDB) 7.12
This GDB was configured as "x86_64-pc-linux-gnu".
```

gdb itself works just fine for what I do.

**Comment by janisozaur** [comment]
I stumbled across this as well, this actually crashes in python 3.6, which was recently released. I worked around this by switching back to python 3.5 (had to compile it locally from ABS, it also required a rebuild of gdb).

**Comment by rocallahan** [comment]
Seems like this is probably a gdb or Python bug? I guess it's probably related to rr's Python scripts, but they shouldn't be able to cause memory corruption from Python.

**Comment by rocallahan** [comment]
Here's the stack trace:
````
#10 0x00007f5b2c4df88a in malloc_printerr (ar_ptr=<optimized out>, ptr=<optimized out>, str=0x7f5b2c5eade8 "double free or corruption (out)", 
    action=3) at malloc.c:5046
#11 _int_free (av=<optimized out>, p=<optimized out>, have_lock=<optimized out>) at malloc.c:3902
#12 0x00007f5b2c4e32bc in __GI___libc_free (mem=<optimized out>) at malloc.c:2982
#13 0x00000000007697ec in PyOS_Readline (sys_stdin=<optimized out>, sys_stdout=<optimized out>, prompt=<optimized out>) at Parser/myreadline.c:359
#14 0x00000000008e0860 in tok_nextc (tok=tok@entry=0x220c3b0) at Parser/tokenizer.c:937
#15 0x00000000008e2280 in tok_get (tok=tok@entry=0x220c3b0, p_start=p_start@entry=0x7ffd30597390, p_end=p_end@entry=0x7ffd30597398)
    at Parser/tokenizer.c:1379
#16 0x00000000008e3119 in PyTokenizer_Get (tok=tok@entry=0x220c3b0, p_start=p_start@entry=0x7ffd30597390, p_end=p_end@entry=0x7ffd30597398)
    at Parser/tokenizer.c:1899
#17 0x00000000008deea1 in parsetok (tok=0x220c3b0, g=<optimized out>, start=256, err_ret=err_ret@entry=0x7ffd30597410, 
    flags=flags@entry=0x7ffd3059740c) at Parser/parsetok.c:208
#18 0x00000000008dfc04 in PyParser_ParseFileObject (fp=<optimized out>, filename=filename@entry=0x7f5b25473458, enc=<optimized out>, 
    g=<optimized out>, start=<optimized out>, ps1=<optimized out>, ps2=0x7f5b25473530 "... ", err_ret=0x7ffd30597410, flags=0x7ffd3059740c)
    at Parser/parsetok.c:134
#19 0x0000000000871a45 in PyParser_ASTFromFileObject (fp=<optimized out>, filename=0x7f5b25473458, enc=<optimized out>, start=<optimized out>, 
    ps1=<optimized out>, ps2=<optimized out>, flags=0x7ffd30597510, errcode=0x7ffd305974cc, arena=0x7f5b2dca8468) at Python/pythonrun.c:1160
#20 0x0000000000871c62 in PyRun_InteractiveOneObject (fp=fp@entry=0x22028c0, filename=filename@entry=0x7f5b25473458, flags=flags@entry=0x7ffd30597510)
    at Python/pythonrun.c:212
#21 0x0000000000871fde in PyRun_InteractiveLoopFlags (fp=0x22028c0, filename_str=filename_str@entry=0x94ecec "<stdin>", flags=0x7ffd30597510, 
    flags@entry=0x0) at Python/pythonrun.c:112
#22 0x00000000004ae74a in python_interactive_command (arg=0x0, from_tty=<optimized out>) at ./python/python.c:345
#23 0x000000000048e363 in cmd_func (cmd=0x20a1cb0, args=0x0, from_tty=0) at ./cli/cli-decode.c:1913
#24 0x0000000000642ba3 in execute_command (p=<optimized out>, p@entry=0x22060a0 "import re", from_tty=0) at top.c:674
#25 0x000000000057e85c in command_handler (command=0x22060a0 "import re") at event-top.c:628
#26 0x00000000006434a8 in read_command_file (stream=stream@entry=0x22028c0) at top.c:481
#27 0x000000000049047d in script_from_file (stream=stream@entry=0x22028c0, file=file@entry=0x7ffd30598fc7 "/proc/2877/fd/4")
    at ./cli/cli-script.c:1703
#28 0x0000000000492983 in source_script_from_stream (file_to_open=0x7ffd30598fc7 "/proc/2877/fd/4", file=0x7ffd30598fc7 "/proc/2877/fd/4", 
---Type <return> to continue, or q <return> to quit---
    stream=0x22028c0) at ./cli/cli-cmds.c:578
#29 source_script_with_search (file=0x7ffd30598fc7 "/proc/2877/fd/4", from_tty=<optimized out>, search_path=<optimized out>) at ./cli/cli-cmds.c:618
#30 0x00000000005773c8 in catch_command_errors_const (command=0x492ad0 <source_script(char const*, int)>, arg=0x7ffd30598fc7 "/proc/2877/fd/4", 
    from_tty=1) at main.c:402
#31 0x0000000000578297 in captured_main (data=0x7ffd30597710) at main.c:1122
#32 gdb_main (args=args@entry=0x7ffd30597830) at main.c:1159
#33 0x000000000040cef5 in main (argc=<optimized out>, argv=<optimized out>) at gdb.c:32
````

**Comment by rocallahan** [comment]
OK, this is a pretty simple bug in gdb. It got fixed upstream two days ago:
https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commit;h=6f8b04077b0c3dc697b1c2bb042c69413d9813b8

There's also this patch:
https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commit;h=b1ce65684d5f92f281d678581f0569cb16fa58e3

So gdb is currently just broken with Python 3.6 until those patches are released/backported.

**Comment by rocallahan** [comment]
Note that the error reported here looks different from the error message in the patch commit message, but it's the same underlying problem AFAICT: gdb allocates the string with PyMem_Malloc, but Python deallocates it with PyMem_RawFree, so there's an allocator mismatch.

**Comment by rocallahan** [comment]
I built gdb from git dcd310a08c9ab601b9dc883e706371f1232cdfef and things seem to work OK.

**Comment by rocallahan** [comment]
Closing this as not an rr issue. I kind of doubt we could work around this in rr.
