### ISSUE TITLE
Crash when printing variable in rr 5.2.0 trace using gdb 7.11.1 

### ISSUE THREAD

**Issue by ddcc** [mozilla/rr#2225]
Not sure if this is a bug in rr or in gdb, but I'm getting a segfault in gdb when I print a variable during replay of an rr trace. This is using rr 5.2.0 with gdb 7.11.1-0ubuntu1~16.5 on Ubuntu 16.04. I have a coredump and application source available, but prefer not to post them publicly.

I captured a trace of an application using rr:
```
rr ./bayes/bayes -v32 -r4096 -n10 -p40 -i2 -e8 -s1 -t4
```

It replays fine, and breaks at the point where the application triggers an assertion:
```
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /mnt/data/sources/stamp/bayes/bayes...done.
Remote debugging using 127.0.0.1:15896
Reading symbols from /lib64/ld-linux-x86-64.so.2...Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/ld-2.23.so...done.
done.
0x00007f6fb6ae0c30 in _start () from /lib64/ld-linux-x86-64.so.2

...

Thread 2 received signal SIGABRT, Aborted.
[Switching to Thread 80761.80762]
0x0000000070000002 in ?? ()

```

I move up to the stack frame of the function that makes the `assert()` call:

```
(rr) up
#1  0x00007f6fb68b75ba in _raw_syscall () at /home/roc/rr/rr/src/preload/raw_syscall.S:120
120     /home/roc/rr/rr/src/preload/raw_syscall.S: No such file or directory.
(rr)
#2  0x00007f6fb68b3cd5 in traced_raw_syscall (call=call@entry=0x7f6fb53b5fa0) at /home/roc/rr/rr/src/preload/syscallbuf.c:222
222     /home/roc/rr/rr/src/preload/syscallbuf.c: No such file or directory.
(rr)
#3  0x00007f6fb68b6389 in syscall_hook_internal (call=0x7f6fb53b5fa0) at /home/roc/rr/rr/src/preload/syscallbuf.c:2653
2653    in /home/roc/rr/rr/src/preload/syscallbuf.c
(rr)
#4  syscall_hook (call=0x7f6fb53b5fa0) at /home/roc/rr/rr/src/preload/syscallbuf.c:2687
2687    in /home/roc/rr/rr/src/preload/syscallbuf.c
(rr)
#5  0x00007f6fb68b3b3a in _syscall_hook_trampoline () at /home/roc/rr/rr/src/preload/syscall_hook.S:282
282     /home/roc/rr/rr/src/preload/syscall_hook.S: No such file or directory.
(rr)
#6  0x00007f6fb68b3b6a in __morestack () at /home/roc/rr/rr/src/preload/syscall_hook.S:417
417     in /home/roc/rr/rr/src/preload/syscall_hook.S
(rr)
#7  0x00007f6fb68b3b88 in _syscall_hook_trampoline_48_3d_00_f0_ff_ff () at /home/roc/rr/rr/src/preload/syscall_hook.S:428
428     in /home/roc/rr/rr/src/preload/syscall_hook.S
(rr)
#8  0x00007f6fb5df042e in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(rr)
#9  0x00007f6fb5df202a in __GI_abort () at abort.c:89
89      abort.c: No such file or directory.
(rr)
#10 0x00007f6fb5de8bd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x4366d1 "params->leaf == 1",
    file=file@entry=0x4365a0 "../lib/list.c", line=line@entry=791,
    function=function@entry=0x43b196 <__PRETTY_FUNCTION__.4892> "merge") at assert.c:92
92      assert.c: No such file or directory.
(rr)
#11 0x00007f6fb5de8c82 in __GI___assert_fail (assertion=0x4366d1 "params->leaf == 1", file=0x4365a0 "../lib/list.c", line=791,
    function=0x43b196 <__PRETTY_FUNCTION__.4892> "merge") at assert.c:101
101     in assert.c
(rr)
#12 0x000000000040c529 in merge (params=0x7f6fb5bb5560, initial=1) at ../lib/list.c:791
791                 ASSERT(params->leaf == 1);
(rr)
```

But when I print an input argument of that function, it crashes the debugger:
```
(rr) p dataPtr
Segmentation fault (core dumped)
```

When I examine the backtrace of the gdb coredump using gdb:
```
#0  0x0000000000561ecf in follow_static_link (static_link=<optimized out>, frame=0x2949050)
    at /build/gdb-9un5Xp/gdb-7.11.1/gdb/findvar.c:438
#1  get_hosting_frame (frame=<optimized out>, var_block=0x28618e0, var=0x2860ef0) at /build/gdb-9un5Xp/gdb-7.11.1/gdb/findvar.c:524
#2  default_read_var_value (var=0x2860ef0, var_block=0x28618e0, frame=<optimized out>)
    at /build/gdb-9un5Xp/gdb-7.11.1/gdb/findvar.c:589
#3  0x0000000000575fae in evaluate_subexp_standard (expect_type=expect_type@entry=0x0, exp=exp@entry=0x20201d0,
    pos=0x7ffe440390a4, noside=noside@entry=EVAL_NORMAL) at /build/gdb-9un5Xp/gdb-7.11.1/gdb/eval.c:773
#4  0x000000000066d1c4 in evaluate_subexp_c (expect_type=0x0, exp=0x20201d0, pos=0x7ffe440390a4, noside=EVAL_NORMAL)
    at /build/gdb-9un5Xp/gdb-7.11.1/gdb/c-lang.c:716
#5  0x00000000005735bd in evaluate_expression (exp=<optimized out>) at /build/gdb-9un5Xp/gdb-7.11.1/gdb/eval.c:163
#6  0x000000000058bf8d in print_command_1 (exp=0x1a05e72 "dataPtr", voidprint=1)
    at /build/gdb-9un5Xp/gdb-7.11.1/gdb/printcmd.c:1002
#7  0x000000000069dbc6 in execute_command (p=<optimized out>, p@entry=0x1a05e70 "p dataPtr", from_tty=1)
    at /build/gdb-9un5Xp/gdb-7.11.1/gdb/top.c:475
#8  0x00000000005d490c in command_handler (command=0x1a05e70 "p dataPtr") at /build/gdb-9un5Xp/gdb-7.11.1/gdb/event-top.c:491
#9  0x00000000005d4fef in command_line_handler (rl=<optimized out>) at /build/gdb-9un5Xp/gdb-7.11.1/gdb/event-top.c:690
#10 0x00002aeae01b76f5 in rl_callback_read_char () from /lib/x86_64-linux-gnu/libreadline.so.6
#11 0x00000000005d4969 in rl_callback_read_char_wrapper (client_data=<optimized out>)
    at /build/gdb-9un5Xp/gdb-7.11.1/gdb/event-top.c:171
#12 0x00000000005d49b3 in stdin_event_handler (error=<optimized out>, client_data=0x0)
    at /build/gdb-9un5Xp/gdb-7.11.1/gdb/event-top.c:430
#13 0x00000000005d3795 in gdb_wait_for_event (block=block@entry=1) at /build/gdb-9un5Xp/gdb-7.11.1/gdb/event-loop.c:834
#14 0x00000000005d3939 in gdb_do_one_event () at /build/gdb-9un5Xp/gdb-7.11.1/gdb/event-loop.c:323
#15 0x00000000005d3a7e in start_event_loop () at /build/gdb-9un5Xp/gdb-7.11.1/gdb/event-loop.c:347
#16 0x00000000005cd443 in captured_command_loop (data=data@entry=0x0) at /build/gdb-9un5Xp/gdb-7.11.1/gdb/main.c:318
#17 0x00000000005ca25d in catch_errors (func=func@entry=0x5cd430 <captured_command_loop>, func_args=func_args@entry=0x0,
    errstring=errstring@entry=0x7abfeb "", mask=mask@entry=RETURN_MASK_ALL) at /build/gdb-9un5Xp/gdb-7.11.1/gdb/exceptions.c:240
#18 0x00000000005ce036 in captured_main (data=data@entry=0x7ffe440394f0) at /build/gdb-9un5Xp/gdb-7.11.1/gdb/main.c:1157
#19 0x00000000005ca25d in catch_errors (func=func@entry=0x5cd990 <captured_main>, func_args=func_args@entry=0x7ffe440394f0,
    errstring=errstring@entry=0x7abfeb "", mask=mask@entry=RETURN_MASK_ALL) at /build/gdb-9un5Xp/gdb-7.11.1/gdb/exceptions.c:240
#20 0x00000000005ce90b in gdb_main (args=args@entry=0x7ffe440394f0) at /build/gdb-9un5Xp/gdb-7.11.1/gdb/main.c:1165
#21 0x000000000045ecd5 in main (argc=<optimized out>, argv=<optimized out>) at /build/gdb-9un5Xp/gdb-7.11.1/gdb/gdb.c:32
```

**Comment by ddcc** [comment]
Yes, this is in research code that is using nested functions, local labels, and some other GCC-specific extensions.

Thanks, I'll try a newer version of gdb.
