### ISSUE TITLE
Assertion `ticks_now == trace_ticks' failed to hold. ticks mismatch for 'SYSCALL: munmap'

### ISSUE THREAD

**Issue by MatsPalmgren** [mozilla/rr#2373]
I'm getting some rr assertions lately when trying to debug Firefox trunk:
```
[FATAL /home/roc/rr/rr/src/ReplaySession.cc:1023:check_ticks_consistency()] 
 (task 940 (rec:32755) at time 4946)
 -> Assertion `ticks_now == trace_ticks' failed to hold. ticks mismatch for 'SYSCALL: munmap'; expected 107546708, got 107546691
=== Start rr backtrace:
rr(_ZN2rr13dump_rr_stackEv+0x28)[0x55faa8]
rr(_ZN2rr9GdbServer15emergency_debugEPNS_4TaskE+0x385)[0x49c9e5]
rr(_ZN2rr21EmergencyDebugOstreamD2Ev+0xd6)[0x4a8656]
rr(_ZN2rr13ReplaySession23check_ticks_consistencyEPNS_10ReplayTaskERKNS_5EventE+0x16d)[0x50c0dd]
rr(_ZN2rr13ReplaySession11replay_stepERKNS0_15StepConstraintsE+0x30b)[0x511c3b]
rr(_ZN2rr14ReplayTimeline19replay_step_forwardENS_10RunCommandEl+0xc3)[0x527543]
rr(_ZN2rr9GdbServer14debug_one_stepERNS_10GdbRequestE+0xe20)[0x49b100]
rr(_ZN2rr9GdbServer12serve_replayERKNS0_15ConnectionFlagsE+0x4c0)[0x49c2c0]
rr[0x50750e]
rr(_ZN2rr13ReplayCommand3runERSt6vectorISsSaISsEE+0x7cb)[0x508d3b]
rr(main+0x244)[0x452504]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb)[0x7f6dd677109b]
rr[0x4529ef]
=== End rr backtrace
Launch gdb with
  gdb '-l' '10000' '-ex' 'set sysroot /' '-ex' 'target extended-remote 127.0.0.1:1025' /md1/objdir/md1/src/inbound/dist/bin/firefox
^Z
[1]+  Stopped                 rr replay
# bg
[1]+ rr replay &
# gdb '-l' '10000' '-ex' 'set sysroot /' '-ex' 'target extended-remote 127.0.0.1:1025' /md1/objdir/md1/src/inbound/dist/bin/firefox
(gdb) bt 20
#0  0x0000000070000002 in  ()
#1  0x00007fdaa2f5b5ba in _raw_syscall () at /home/roc/rr/rr/src/preload/raw_syscall.S:120
#2  0x00007fdaa2f57cd5 in traced_raw_syscall (call=call@entry=0x681fffa0) at /home/roc/rr/rr/src/preload/syscallbuf.c:222
#3  0x00007fdaa2f5a389 in syscall_hook_internal (call=0x681fffa0) at /home/roc/rr/rr/src/preload/syscallbuf.c:2653
#4  0x00007fdaa2f5a389 in syscall_hook (call=0x681fffa0) at /home/roc/rr/rr/src/preload/syscallbuf.c:2687
#5  0x00007fdaa2f57b3a in _syscall_hook_trampoline () at /home/roc/rr/rr/src/preload/syscall_hook.S:282
#6  0x00007fdaa2f57b6a in __morestack () at /home/roc/rr/rr/src/preload/syscall_hook.S:417
#7  0x00007fdaa2f57b70 in _syscall_hook_trampoline_48_3d_01_f0_ff_ff () at /home/roc/rr/rr/src/preload/syscall_hook.S:423
#8  0x00007fdaa2af949d in munmap () at ../sysdeps/unix/syscall-template.S:78
#9  0x00007fda997ede53 in mdb_env_close1 (env=0x7fdaa279e700) at lmdb/libraries/liblmdb/mdb.c:5089
#10 0x00007fda997edf33 in mdb_env_close (env=<optimized out>) at lmdb/libraries/liblmdb/mdb.c:5163
#11 0x00007fda98472fb9 in <lmdb::environment::Environment as core::ops::drop::Drop>::drop (self=0x7fffbf32cdb0) at /md1/src/inbound/third_party/rust/lmdb-rkv/src/environment.rs:353
#12 0x00007fda99278ac6 in core::ptr::real_drop_in_place () at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ptr.rs:195
#13 0x00007fda9927900d in core::ptr::real_drop_in_place () at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ptr.rs:195
#14 0x00007fda992789c5 in core::ptr::real_drop_in_place () at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ptr.rs:195
#15 0x00007fda96ff35fa in xulstore::statics::cache_data () at toolkit/components/xulstore/src/statics.rs:219
#16 0x00007fda992781df in <xulstore::statics::DATA_CACHE as core::ops::deref::Deref>::deref::__static_ref_initialize () at toolkit/components/xulstore/src/statics.rs:43
#17 0x00007fda992781df in core::ops::function::FnOnce::call_once () at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ops/function.rs:231
#18 0x00007fda997c1ce4 in lazy_static::lazy::Lazy<T>::get::{{closure}} () at /md1/src/inbound/third_party/rust/lazy_static/src/inline_lazy.rs:28
#19 0x00007fda9929b30d in std::sync::once::Once::call_once::{{closure}} () at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/sync/once.rs:220
(More stack frames follow...)
(gdb) q
# rr dump -b -m -p /home/mats/.local/share/rr/firefox-1/ 4946
{
  real_time:2523.381280 global_time:4946, event:`SYSCALL: munmap' (state:ENTERING_SYSCALL) tid:32755, ticks:107546708
rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x2 rsi:0x100000 rdi:0x7fda86fff000 rbp:0xb rsp:0x681ffe00 r8:0x0 r9:0x80000000 r10:0x58 r11:0x246 r12:0x7fda991f3850 r13:0x0 r14:0x7fdaa279e700 r15:0x38 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xb fs_base:0x7fdaa29e2780 gs_base:0x0
}

```

I'm using rr version 5.2.0 on a fully updated Ubuntu 18.10 (kernel 4.18.0-25-generic).

**Comment by rocallahan** [comment]
Try rr master?

**Comment by khuey** [comment]
You need to use rr master. This has been fixed there.

**Comment by MatsPalmgren** [comment]
Yup, using rr master fixed it.  Thanks for the quick reply!
