### ISSUE TITLE
`rr replay` doesn't stop on exit and reports SIGKILL instead

### ISSUE THREAD

**Issue by milianw** [mozilla/rr#2378]
it seems like `rr replay` continues to run code after exit, leading to a confusing message:

```
Program received signal SIGKILL, Killed.
```

To reproduce, I can record basically any command and the run `continue` within `rr replay`.

```
$ rr record ls
rr: Saving execution to trace directory `/home/milian/.local/share/rr/ls-1'.

// output from ls

$ echo $?
0
```
So far so good, but now:

```
$ rr replay
GNU gdb (GDB) 8.3
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/ls...
(No debugging symbols found in /usr/bin/ls)
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
Remote debugging using 127.0.0.1:17819
Reading symbols from /lib64/ld-linux-x86-64.so.2...
(No debugging symbols found in /lib64/ld-linux-x86-64.so.2)
0x00007f13fe9f0100 in _start () from /lib64/ld-linux-x86-64.so.2
(rr) c
Continuing.

// output from ls

Program received signal SIGKILL, Killed.
0x0000000070000002 in ?? ()
```

This is quite confusing for novices. Can this be handled somehow? GDB would show the following instead:

```
[Inferior 1 (process 18184) exited normally]
```

Ideally, `rr` would not let the process exit, but stop right before, such that we can continue to step backwards again.

Below, you can see what happens when one steps back from the SIGKILL. In the case of `ls` it seems to me like it's executing some code after exit? I mean, ls shouldn't do a stat syscal from an exit handler, or? It's quite bogus imo:

```
Program received signal SIGKILL, Killed.
0x0000000070000002 in ?? ()
(rr) bt
#0  0x0000000070000002 in ?? ()
Backtrace stopped: Cannot access memory at address 0x681ffe10
(rr) rni
_raw_syscall () at /home/milian/projects/src/rr/src/preload/raw_syscall.S:120
120             callq *32(%rsp)
(rr) 
118             movq $-1,%rcx
(rr) 
117             movq $0x246,%r11
(rr) 
115             xor %ecx,%ecx
(rr) 
73              pushq 32(%rsp)
(rr) 
71              pushq 32(%rsp)
(rr) 
69              movq 8(%rsp), %r9       /* sixth syscall arg */
(rr) 
68              movq %r9, %r8           /* fifth syscall arg */
(rr) 
67              movq %r8, %r10          /* fourth syscall arg */
(rr) 
66              movq %rcx, %rdx         /* third syscall arg */
(rr) 
65              movq %rdx, %rsi         /* second syscall arg */
(rr) 
64              movq %rsi, %rdi         /* first syscall arg */
(rr) 
63              movq %rdi, %rax         /* syscall number */
(rr) 
0x00007f13fe9bdca9 in traced_raw_syscall (call=call@entry=0x681fffa0) at /home/milian/projects/src/rr/src/preload/syscallbuf.c:225
warning: Source file is more recent than executable.
225      */
(rr) 
0x00007f13fe9bdca7      225      */
(rr) 
0x00007f13fe9bdca3      225      */
(rr) 
0x00007f13fe9bdc9f      225      */
(rr) 
0x00007f13fe9bdc9c      225      */
(rr) 
0x00007f13fe9bdc97      225      */
(rr) 
0x00007f13fe9bdc95      225      */
(rr) 
0x00007f13fe9bdc93      225      */
(rr) 
0x00007f13fe9bdc90      225      */
(rr) 
0x00007f13fe9bdc8c      225      */
(rr) 
0x00007f13fe9bdc88      225      */
(rr) 
0x00007f13fe9bdc84      225      */
(rr) 
225      */
(rr) 
0x00007f13fe9bf315 in sys_statfs (call=<optimized out>) at /home/milian/projects/src/rr/src/preload/syscallbuf.c:2633
2633       * a traced syscall.
(rr) 
2633       * a traced syscall.
(rr) 
0x00007f13fe9bf1e8 in syscall_hook_internal (call=0x681fffa0) at /home/milian/projects/src/rr/src/preload/syscallbuf.c:2898
2898    static void do_delay(void) {
(rr) 
0x00007f13fe9bf1e5      2898    static void do_delay(void) {
(rr) 
0x00007f13fe9bf1e1      2898    static void do_delay(void) {
(rr) 
0x00007f13fe9bf1da      2898    static void do_delay(void) {
(rr) 
0x00007f13fe9bf1d4      2898    static void do_delay(void) {
(rr) 
0x00007f13fe9bf1cd      2898    static void do_delay(void) {
(rr) 
2898    static void do_delay(void) {
(rr) 
0x00007f13fe9bf1a9 in syscall_hook (call=0x681fffa0) at /home/milian/projects/src/rr/src/preload/syscallbuf.c:2894
2894      }
(rr) 
2894      }
(rr) 
2892        default:
(rr) 
0x00007f13fe9bf198      130      * Return a pointer to the buffer header, which happens to occupy the
(rr) 
0x00007f13fe9bf196      130      * Return a pointer to the buffer header, which happens to occupy the
(rr) 
130      * Return a pointer to the buffer header, which happens to occupy the
(rr) 
0x00007f13fe9bf190      2887        case SYS_fstatfs:
(rr) 
0x00007f13fe9bf18d      2887        case SYS_fstatfs:
(rr) 
2887        case SYS_fstatfs:
(rr) 
0x00007f13fe9beecf in init_thread () at /home/milian/projects/src/rr/src/preload/syscallbuf.c:2885
2885          return sys_xstat64(call);
(rr) 
0x00007f13fe9beecc      2885          return sys_xstat64(call);
(rr) 
0x00007f13fe9beec4      2885          return sys_xstat64(call);
(rr) 
0x00007f13fe9beebd in syscall_hook (call=0x681fffa0) at /home/milian/projects/src/rr/src/preload/syscallbuf.c:2885
2885          return sys_xstat64(call);
(rr) 
0x00007f13fe9beeba      2885          return sys_xstat64(call);
(rr) 
0x00007f13fe9beeb9      2885          return sys_xstat64(call);
(rr) 
0x00007f13fe9beeb8      2885          return sys_xstat64(call);
(rr) 
0x00007f13fe9beeb6      2885          return sys_xstat64(call);
(rr) 
0x00007f13fe9beeb4      2885          return sys_xstat64(call);
(rr) 
0x00007f13fe9beeb2      2885          return sys_xstat64(call);
(rr) 
2885          return sys_xstat64(call);
(rr) 
_syscall_hook_trampoline () at /home/milian/projects/src/rr/src/preload/syscall_hook.S:282
282             callq syscall_hook
(rr) 
281             mov %rbx,%rdi
(rr) 
278             and $0xfffffffffffffff0,%rsp
(rr) 
276             mov %rsp,%rbx
(rr) 
271             pushq %rax
(rr) 
268             pushq %rdi
(rr) 
265             pushq %rsi
(rr) 
262             pushq %rdx
(rr) 
259             pushq %r10
(rr) 
256             pushq %r8
(rr) 
253             pushq %r9
(rr) 
247             pushq %rbx
(rr) 
__morestack () at /home/milian/projects/src/rr/src/preload/syscall_hook.S:417
417     callq _syscall_hook_trampoline
(rr) 
_syscall_hook_trampoline_48_3d_00_f0_ff_ff () at /home/milian/projects/src/rr/src/preload/syscall_hook.S:428
428             callq __morestack
(rr) 
0x00007f13fe970308 in ?? ()
(rr) 
0x00007f13fe970300 in ?? ()
(rr) 
0x00007f13fe9702f9 in ?? ()
(rr) 
0x00007f13fe9702f8 in ?? ()
(rr) 
0x00007f13fe9702f1 in ?? ()
(rr) 
0x00007f13fe9702e8 in ?? ()
(rr) 
0x00007f13fe9702e0 in ?? ()
(rr) 
0x00007f13fe9702de in ?? ()
(rr) 
0x00007f13fe9702d6 in ?? ()
(rr) 
0x00007f13fe9702cf in ?? ()
(rr) 
0x00007f13fe9702c7 in ?? ()
(rr) 
0x00007f13fe86e634 in _exit () from /usr/lib/libc.so.6
(rr) bt
#0  0x00007f13fe86e634 in _exit () from /usr/lib/libc.so.6
#1  0x00007f13fe7e1f32 in __run_exit_handlers () from /usr/lib/libc.so.6
#2  0x00007f13fe7e1fae in exit () from /usr/lib/libc.so.6
#3  0x00007f13fe7cbeea in __libc_start_main () from /usr/lib/libc.so.6
#4  0x0000555d73cfdb0e in ?? ()
```

**Comment by rocallahan** [comment]
This is a deliberate choice. It's very useful to be able to inspect the state at the moment the process exits, and it's also very useful to be able to reverse-continue from there.

It looks like you're in a stat call because you're actually in librrpreload code that is optimized so some stat-handling code is merged with code that executes an exit syscall.

**Comment by milianw** [comment]
but why does GDB report a SIGKILL? Is that caused by the exit syscall handler? Could it maybe trigger some GDB output before, to clarify that the SIGKILL is expected and used to prevent the app from really exiting?

**Comment by rocallahan** [comment]
rr reports a fake SIGKILL to gdb just before exiting the process.

I don't think there's a way for a remote agent to tell gdb to print something.

**Comment by milianw** [comment]
too bad, I'll close this then
