### ISSUE TITLE
recording chromium-browser is slow

### ISSUE THREAD

**Issue by rocallahan** [mozilla/rr#2383]
This is to track some issues I've found recording `chromium-browser --disable-gpu` in Fedora 30.

**Comment by rocallahan** [comment]
Just starting the browser and then trying to type in the URL bar is really slow. So slow that at some point (after 3 minutes) I just give up waiting for more characters to appear and kill rr.

**Comment by rocallahan** [comment]
[rr ps](https://github.com/mozilla/rr/files/3507481/rr-ps.txt) shows 96 processes being started. This is bad; process spawning is kinda slow under rr because ld.so has to do a bunch of work before the preload library is initialized and syscall buffering happens. (Also a lot of ld.so's syscalls, e.g. mmap, can't be buffered anyway.)

Most of these processes appear to be launched via `xdg-settings check default-web-browser chromium-browser.desktop`. Using `chromium-browser --no-default-browser-check` should probably avoid that, but it doesn't.

**Comment by rocallahan** [comment]
Out of 180K events I see about 10K unbuffered pread64 events, which seem to be coming from here: https://chromium.googlesource.com/chromium/src/+/lkgr/base/debug/stack_trace_posix.cc#604
It's using pread on `/proc/self/mem`, which we disable buffering for because we want to catch writes to process memory. We could pretty easily make this fast by extending `FileMonitor` and `syscallbuf_fds_disabled` to indicate whether buffered reads of the file are allowed.

**Comment by rocallahan** [comment]
This problem is especially bad in Fedora's Chromium build because for some reason they disable linking all the libraries together libxul-style, so each Chromium process contains 248 Chromium libraries.

**Comment by rocallahan** [comment]
I'm trying google-chrome-unstable instead. That seems to perform better, but crashes rr with `[FATAL /home/roc/rr/rr/src/record_syscall.cc:4645:monitor_fd_for_mapping() errno: EACCES] Can't open fd directory /proc/15693/fd`.

**Comment by rocallahan** [comment]
Fixed that with 16284e6868475a935887bd3ea99df4b91bb7723e.

**Comment by rocallahan** [comment]
With that fixed, google-chrome-unstable performs okay. Not great but it is kinda usable; I can load lwn.net, scroll around, and then exit the browser. I should probably stop here.

I have noticed that out of 250K events in the resulting trace, about 10% are traced openat calls. Most of those are called via a stack like this:
```
#0  0x00007fc3b5f7eee0 in __libc_openat64 (fd=fd@entry=203, file=file@entry=0xc96661d03f1 "sys", oflag=oflag@entry=2752512) at ../sysdeps/unix/sysv/linux/openat64.c:35
#1  0x00007fc39861c594 in openat64 (__oflag=2752512, __path=0xc96661d03f1 "sys", __fd=203, __fd=<optimized out>, __path=<optimized out>, __oflag=<optimized out>)
    at /usr/include/bits/fcntl2.h:129
#2  0x00007fc39861c594 in chase_symlinks (path=0x7fc394051f50 "/sys/bus/acpi/devices/PNP0C0F:05", original_root=<optimized out>, flags=0, ret=0x7fc394051ed8)
    at ../src/basic/fs-util.c:900
#3  0x00007fc398620640 in device_set_syspath (device=0xc96660903c0, _syspath=0x7fc394051f50 "/sys/bus/acpi/devices/PNP0C0F:05", verify=<optimized out>)
    at ../src/libsystemd/sd-device/sd-device.c:148
#4  0x00007fc398625468 in sd_device_new_from_syspath (ret=0x7fc394052010, syspath=0x7fc394051f50 "/sys/bus/acpi/devices/PNP0C0F:05")
    at ../src/libsystemd/sd-device/sd-device.c:223
#5  0x00007fc398628443 in enumerator_scan_dir_and_add_devices (enumerator=0xc96663bbc80, basedir=<optimized out>, subdir1=<optimized out>, subdir2=<optimized out>)
    at ../src/libsystemd/sd-device/device-enumerator.c:471
#6  0x00007fc398628891 in enumerator_scan_dir (enumerator=0xc96663bbc80, basedir=<optimized out>, subdir=<optimized out>, subsystem=0x0)
    at ../src/libsystemd/sd-device/device-enumerator.c:568
#7  0x00007fc39862b25f in enumerator_scan_devices_all (enumerator=0xc96663bbc80) at ../src/libsystemd/sd-device/device-enumerator.c:777
#8  0x00007fc39862b25f in device_enumerator_scan_devices (enumerator=0xc96663bbc80) at ../src/libsystemd/sd-device/device-enumerator.c:844
#9  0x00007fc39862b25f in udev_enumerate_scan_devices (udev_enumerate=<optimized out>) at ../src/libudev/libudev-enumerate.c:377
```
This `udev_enumerate_scan_devices` call doesn't actually finish before I've exited the browser. I'm not sure exactly what's happening here but this code appears to call `chase_symlinks` at least once per entry in `/sys/bus/*/devices/*`, and there are 727 of those on my system. And `chase_symlinks` call openat 14 times for `/sys/bus/acpi/devices/PNP0C0F:05`, for example. These openat calls aren't buffered because they pass in a valid `dirfd`, so we drop back to rr because they might be opening a special file we need to monitor.

**Comment by rocallahan** [comment]
I *guess* syscallbuf openat with a valid dirfd could try opening the file, then try readlink on /proc/self/fd/<fd> and check the filename against that.

**Comment by rocallahan** [comment]
48e841d20e22f4aca621b70ada7424f7ce98ad82 adds syscall buffering for openat with a valid dirfd. f50761c02cb743e02bd35cf882c740b5f075dc3c fixes syscall buffering for a lot of simple syscalls with my new glibc (which is compiled for CET so has different instruction layouts than older glibcs). cbe18bc1807c9bcc822ba7119d112c3aec2ec0fc add syscall buffering for readlinkat which was showing up a bit and is trivial to optimize.

I'm done here.

**Comment by rocallahan** [comment]
FWIW with these changes recording Fedora's chromium-browser is still slow, slower than google-chrome-unstable, but significantly faster than before. I can actually record startup, load page and shutdown in a reasonable amount of time now.
