### ISSUE TITLE
rr hangs on Comet Lake

### ISSUE THREAD

**Issue by slopedog** [mozilla/rr#2407]
I built rr from master today (221ae40) on an Ubuntu 18.04 system. The machine is using a Comet Lake CPU. The executable is a C++ program that just prints "hello". It never returns after doing `run`, whether or not I have breakpoints. If I use ctrl-c, it will come back to the `gdb` prompt if I hit enter. Here is what I'm running:
```
jah@jah-XPS-13-7390:/tmp$ g++ -g3 -O0 hello.cpp 
jah@jah-XPS-13-7390:/tmp$ rr record ./a.out
rr: Saving execution to trace directory `/home/jah/.local/share/rr/a.out-1'.
hello
jah@jah-XPS-13-7390:/tmp$ rr replay
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/jah/.local/share/rr/a.out-1/mmap_copy_3_a.out...done.
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
Remote debugging using 127.0.0.1:6385
Reading symbols from /lib64/ld-linux-x86-64.so.2...Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/ld-2.27.so...done.
done.
0x00007f8237267090 in _start () from /lib64/ld-linux-x86-64.so.2
(rr) run
```

`strace` output after typing `run<enter>`:
```
read(0, "\r", 1)                        = 1
write(1, "\n", 1
)                       = 1
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_STOP or TCSETSW, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
rt_sigaction(SIGINT, {sa_handler=0x55a1230bd2f0, sa_mask=[INT], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fbd66ba4890}, {sa_handler=0x7fbd67cffdf0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbd66ba4890}, 8) = 0
rt_sigaction(SIGTERM, {sa_handler=0x55a1230bd320, sa_mask=[TERM], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fbd66ba4890}, {sa_handler=0x7fbd67cffdf0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbd66ba4890}, 8) = 0
rt_sigaction(SIGHUP, {sa_handler=0x55a1230bd150, sa_mask=[HUP], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fbd66ba4890}, {sa_handler=0x7fbd67cffdf0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbd66ba4890}, 8) = 0
rt_sigaction(SIGQUIT, {sa_handler=0x55a1230bd170, sa_mask=[QUIT], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fbd66ba4890}, {sa_handler=0x7fbd67cffdf0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbd66ba4890}, 8) = 0
rt_sigaction(SIGALRM, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbd66ba4890}, {sa_handler=0x7fbd67cffdf0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbd66ba4890}, 8) = 0
rt_sigaction(SIGTSTP, {sa_handler=SIG_DFL, sa_mask=[TSTP], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fbd66ba4890}, {sa_handler=0x7fbd67cffdf0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbd66ba4890}, 8) = 0
rt_sigaction(SIGTTOU, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbd66ba4890}, {sa_handler=0x7fbd67cffdf0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbd66ba4890}, 8) = 0
rt_sigaction(SIGTTIN, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbd66ba4890}, {sa_handler=0x7fbd67cffdf0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbd66ba4890}, 8) = 0
rt_sigaction(SIGINT, {sa_handler=0x55a1230bd2f0, sa_mask=[INT], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fbd6590cf20}, {sa_handler=0x55a1230bd2f0, sa_mask=[INT], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fbd66ba4890}, 8) = 0
rt_sigaction(SIGTSTP, {sa_handler=0x55a1230bd190, sa_mask=[TSTP], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fbd6590cf20}, {sa_handler=SIG_DFL, sa_mask=[TSTP], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fbd66ba4890}, 8) = 0
```

**Comment by khuey** [comment]
Does `rr replay -a` succeed?

**Comment by slopedog** [comment]
It  does.

**Comment by rocallahan** [comment]
Run with `RR_LOG=all RR_LOG_FILE=/tmp/rr-log` and paste the last 50 lines of the log?

**Comment by slopedog** [comment]
Here are the last 50 before I hit ctrl-c (I don't know if every logging line gets flushed):
```
[GdbConnection] gdb is ready for symbol lookups
[GdbConnection] write_flush: '$qSymbol:5f7468726561645f64625f726567697374657236345f7468726561645f61726561#c1'
[GdbConnection] raw request qSymbol::5f7468726561645f64625f726567697374657236345f7468726561645f61726561
[GdbConnection] gdb is ready for symbol lookups
[GdbConnection] write_flush: '$qSymbol:5f7468726561645f64625f72746c645f676c6f62616c5f5f646c5f746c735f6474765f736c6f74696e666f5f6c697374#0c'
[GdbConnection] raw request qSymbol::5f7468726561645f64625f72746c645f676c6f62616c5f5f646c5f746c735f6474765f736c6f74696e666f5f6c697374
[GdbConnection] gdb is ready for symbol lookups
[GdbConnection] write_flush: '$qSymbol:5f7468726561645f64625f73697a656f665f6474765f736c6f74696e666f#ba'
[GdbConnection] raw request qSymbol::5f7468726561645f64625f73697a656f665f6474765f736c6f74696e666f
[GdbConnection] gdb is ready for symbol lookups
[GdbConnection] write_flush: '$qSymbol:5f7468726561645f64625f73697a656f665f6474765f736c6f74696e666f5f6c697374#32'
[GdbConnection] raw request qSymbol::5f7468726561645f64625f73697a656f665f6474765f736c6f74696e666f5f6c697374
[GdbConnection] gdb is ready for symbol lookups
[GdbConnection] write_flush: '$qSymbol:5f7468726561645f64625f73697a656f665f6c6973745f74#a4'
[GdbConnection] raw request qSymbol::5f7468726561645f64625f73697a656f665f6c6973745f74
[GdbConnection] gdb is ready for symbol lookups
[GdbConnection] write_flush: '$qSymbol:5f7468726561645f64625f73697a656f665f70746872656164#a6'
[GdbConnection] raw request qSymbol::5f7468726561645f64625f73697a656f665f70746872656164
[GdbConnection] gdb is ready for symbol lookups
[GdbConnection] write_flush: '$qSymbol:5f7468726561645f64625f73697a656f665f707468726561645f6b65795f64617461#f2'
[GdbConnection] raw request qSymbol::5f7468726561645f64625f73697a656f665f707468726561645f6b65795f64617461
[GdbConnection] gdb is ready for symbol lookups
[GdbConnection] write_flush: '$qSymbol:5f7468726561645f64625f73697a656f665f707468726561645f6b65795f646174615f6c6576656c32#67'
[GdbConnection] raw request qSymbol::5f7468726561645f64625f73697a656f665f707468726561645f6b65795f646174615f6c6576656c32
[GdbConnection] gdb is ready for symbol lookups
[GdbConnection] write_flush: '$qSymbol:5f7468726561645f64625f73697a656f665f707468726561645f6b65795f737472756374#cd'
[GdbConnection] raw request qSymbol::5f7468726561645f64625f73697a656f665f707468726561645f6b65795f737472756374
[GdbConnection] gdb is ready for symbol lookups
[GdbConnection] write_flush: '$qSymbol:5f7468726561645f64625f73697a656f665f72746c645f676c6f62616c#3d'
[GdbConnection] raw request qSymbol::5f7468726561645f64625f73697a656f665f72746c645f676c6f62616c
[GdbConnection] gdb is ready for symbol lookups
[GdbConnection] write_flush: '$qSymbol:5f7468726561645f64625f73697a656f665f74645f6576656e746275665f74#c0'
[GdbConnection] raw request qSymbol::5f7468726561645f64625f73697a656f665f74645f6576656e746275665f74
[GdbConnection] gdb is ready for symbol lookups
[GdbConnection] write_flush: '$qSymbol:5f7468726561645f64625f73697a656f665f74645f7468725f6576656e74735f74#c7'
[GdbConnection] raw request qSymbol::5f7468726561645f64625f73697a656f665f74645f7468725f6576656e74735f74
[GdbConnection] gdb is ready for symbol lookups
[GdbConnection] write_flush: '$qSymbol:5f7468726561645f64625f74645f6576656e746275665f745f6576656e7464617461#c8'
[GdbConnection] raw request qSymbol::5f7468726561645f64625f74645f6576656e746275665f745f6576656e7464617461
[GdbConnection] gdb is ready for symbol lookups
[GdbConnection] write_flush: '$qSymbol:5f7468726561645f64625f74645f6576656e746275665f745f6576656e746e756d#c6'
[GdbConnection] raw request qSymbol::5f7468726561645f64625f74645f6576656e746275665f745f6576656e746e756d
[GdbConnection] gdb is ready for symbol lookups
[GdbConnection] write_flush: '$qSymbol:5f7468726561645f64625f74645f7468725f6576656e74735f745f6576656e745f62697473#73'
[GdbConnection] raw request qSymbol::5f7468726561645f64625f74645f7468725f6576656e74735f745f6576656e745f62697473
[GdbConnection] gdb is ready for symbol lookups
[GdbConnection] write_flush: '$qSymbol:6e70746c5f76657273696f6e#13'
```

**Comment by slopedog** [comment]
After ctrl-c, enter, `quit`, and `y`, I get this additional output:
```
[GdbConnection] raw request qSymbol::6e70746c5f76657273696f6e
[GdbConnection] gdb is ready for symbol lookups
[GdbConnection] write_flush: '$qSymbol:737461636b5f75736564#a4'
[GdbConnection] raw request qSymbol::737461636b5f75736564
[GdbConnection] gdb is ready for symbol lookups
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request D;1a48
[GdbConnection] gdb is detaching from us
[GdbServer]   debugger detached
[GdbConnection] write_flush: '$OK#9a'
[GdbServer] debugger server exiting ...
[Session] safely detaching from 19595 ...
[Session] sending SIGKILL to 19595 ...
[ThreadGroup] destabilizing thread group 6728
[ThreadGroup]   destabilized task 19595
[Task] task 19595 (rec:6728) is dying ...
[WARN ~Task() errno: ESRCH] 19595 is unstable; not blocking on its termination
[HasTaskSet] removing 19595 from task set 0x5588897442c0
[HasTaskSet] removing 19595 from task set 0x5588897456e0
[HasTaskSet] removing 19595 from task set 0x5588897528b0
[Task]   dead
[Session] Session 0x558889754cc0 destroyed
[Session] safely detaching from 19597 ...
[Session] sending SIGKILL to 19597 ...
[ThreadGroup] destabilizing thread group 6728
[ThreadGroup]   destabilized task 19597
[Task] task 19597 (rec:6728) is dying ...
[WARN ~Task() errno: ESRCH] 19597 is unstable; not blocking on its termination
[HasTaskSet] removing 19597 from task set 0x55888980aa00
[HasTaskSet] removing 19597 from task set 0x5588897448b0
[HasTaskSet] removing 19597 from task set 0x55888980a760
[Task]   dead
[Session] Session 0x5588897afea0 destroyed
[Session] safely detaching from 19594 ...
[Session] sending SIGKILL to 19594 ...
[ThreadGroup] destabilizing thread group 6728
[ThreadGroup]   destabilized task 19594
[Task] task 19594 (rec:6728) is dying ...
[WARN ~Task() errno: ESRCH] 19594 is unstable; not blocking on its termination
[HasTaskSet] removing 19594 from task set 0x5588897454e0
[HasTaskSet] removing 19594 from task set 0x558889743740
[HasTaskSet] removing 19594 from task set 0x5588897433f0
[Task]   dead
[Session] Session 0x558889742ad0 destroyed
```

**Comment by rocallahan** [comment]
Instead of `run` after rr starts, what if you just do `continue`?

**Comment by slopedog** [comment]
That works! What do you think is happening?

**Comment by rocallahan** [comment]
I'm still not sure.

If you set a breakpoint, continue until you hit the breakpoint, then `run`, what happens?

**Comment by slopedog** [comment]
Oddness:
```
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/jah/.local/share/rr/a.out-2/mmap_copy_3_a.out...done.
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
Remote debugging using 127.0.0.1:29711
Reading symbols from /lib64/ld-linux-x86-64.so.2...Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/ld-2.27.so...done.
done.
0x00007fecb29a1090 in _start () from /lib64/ld-linux-x86-64.so.2
(rr) b main
Breakpoint 1 at 0x557406cac8be: file hello.cpp, line 4.
(rr) cont
Continuing.

Breakpoint 1, main () at hello.cpp:4
4	    std::cout << "hello" << std::endl;
(rr) run
Warning: the current language does not match this frame.
```

**Comment by rocallahan** [comment]
So it hangs again?

Once it has hung, what do you get if you connect gdb to rr (gdp -p `pidof rr`) and then get an rr stack trace?

Also, once rr has hung, if you get the pid of the a.out process (pidof rr:a.out I guess), dump /proc/<pid>/stack?

**Comment by slopedog** [comment]
Yes - it hangs. rr stack trace:
```(gdb) bt
#0  0x00007f306037ebc4 in __GI___poll (fds=0x7ffd121d54b8, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x000055b6650625e1 in rr::poll_socket (sock_fd=..., events=1, timeoutMs=-1) at /home/jah/third-party/rr/src/GdbConnection.cc:86
#2  0x000055b66506269a in rr::poll_incoming (sock_fd=..., timeoutMs=-1) at /home/jah/third-party/rr/src/GdbConnection.cc:94
#3  0x000055b665062700 in rr::GdbConnection::read_data_once (this=0x55b667091e20) at /home/jah/third-party/rr/src/GdbConnection.cc:108
#4  0x000055b66506347d in rr::GdbConnection::read_packet (this=0x55b667091e20) at /home/jah/third-party/rr/src/GdbConnection.cc:299
#5  0x000055b6650690bc in rr::GdbConnection::get_request (this=0x55b667091e20) at /home/jah/third-party/rr/src/GdbConnection.cc:1320
#6  0x000055b66507bae3 in rr::GdbServer::process_debugger_requests (this=0x7ffd121d8190, state=rr::GdbServer::REPORT_NORMAL)
    at /home/jah/third-party/rr/src/GdbServer.cc:980
#7  0x000055b66507c9d1 in rr::GdbServer::debug_one_step (this=0x7ffd121d8190, last_resume_request=...)
    at /home/jah/third-party/rr/src/GdbServer.cc:1134
#8  0x000055b66507ebc3 in rr::GdbServer::serve_replay (this=0x7ffd121d8190, flags=...) at /home/jah/third-party/rr/src/GdbServer.cc:1550
#9  0x000055b66515ed3d in rr::replay (trace_dir="", flags=...) at /home/jah/third-party/rr/src/ReplayCommand.cc:483
#10 0x000055b66515f763 in rr::ReplayCommand::run (this=0x55b6655c9400 <rr::ReplayCommand::singleton>, 
    args=std::vector of length 0, capacity 1) at /home/jah/third-party/rr/src/ReplayCommand.cc:603
#11 0x000055b6652181d9 in main (argc=2, argv=0x7ffd121d8768) at /home/jah/third-party/rr/src/main.cc:268
```

rr:a.out has three pids:
```jah@jah-XPS-13-7390:/tmp$ sudo cat /proc/5527/stack 
[<0>] ptrace_stop+0x15b/0x280
[<0>] get_signal+0x4b2/0x7a0
[<0>] do_signal+0x37/0x720
[<0>] exit_to_usermode_loop+0x73/0xd0
[<0>] prepare_exit_to_usermode+0x83/0x90
[<0>] retint_user+0x8/0x8
[<0>] 0xffffffffffffffff
jah@jah-XPS-13-7390:/tmp$ sudo cat /proc/5528/stack 
[<0>] ptrace_stop+0x15b/0x280
[<0>] get_signal+0x4b2/0x7a0
[<0>] do_signal+0x37/0x720
[<0>] exit_to_usermode_loop+0x73/0xd0
[<0>] do_syscall_64+0x121/0x130
[<0>] entry_SYSCALL_64_after_hwframe+0x3d/0xa2
[<0>] 0xffffffffffffffff
jah@jah-XPS-13-7390:/tmp$ sudo cat /proc/5530/stack 
[<0>] ptrace_stop+0x15b/0x280
[<0>] get_signal+0x4b2/0x7a0
[<0>] do_signal+0x37/0x720
[<0>] exit_to_usermode_loop+0x73/0xd0
[<0>] do_syscall_64+0x121/0x130
[<0>] entry_SYSCALL_64_after_hwframe+0x3d/0xa2
[<0>] 0xffffffffffffffff
```

**Comment by rocallahan** [comment]
So we hang waiting for input from gdb. Interesting.

Does reverting rr commit 94e4013db3fcc416a6ca2c84fd9296a5bbe2e34c fix it?

**Comment by rocallahan** [comment]
Sorry I mean reverting 221ae405b2c69e01b8042f268561fa466e940e9d

**Comment by slopedog** [comment]
That seems to have fixed the problem.

**Comment by rocallahan** [comment]
OK I've backed that out to fix the bug.
