### ISSUE TITLE
rr can unmap its own TLS memory and subsequently SIGSEGV

### ISSUE THREAD

**Issue by ddcc** [mozilla/rr#2608]
I was trying to track down a bug in a program, but discovered that it was causing rr to segfault:

```
Thread 1 "rr" received signal SIGSEGV, Segmentation fault.
0x00007ffff7fe9d1d in __tls_get_addr () from /lib64/ld-linux-x86-64.so.2
(gdb) bt
#0  0x00007ffff7fe9d1d in __tls_get_addr () from /lib64/ld-linux-x86-64.so.2
#1  0x00007ffff7d1e6c4 in __cxa_get_globals () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007ffff7e876ed in kj::_::uncaughtExceptionCount() () from /usr/lib/x86_64-linux-gnu/libkj-0.7.0.so
#3  0x00007ffff7e8770d in kj::UnwindDetector::UnwindDetector() () from /usr/lib/x86_64-linux-gnu/libkj-0.7.0.so
#4  0x00007ffff7e8d1c5 in kj::BufferedOutputStreamWrapper::BufferedOutputStreamWrapper(kj::OutputStream&, kj::ArrayPtr<unsigned char>) () from /usr/lib/x86_64-linux-gnu/libkj-0.7.0.so
#5  0x00007ffff7f4bc28 in capnp::writePackedMessage(kj::OutputStream&, kj::ArrayPtr<kj::ArrayPtr<capnp::word const> const>) () from /usr/lib/x86_64-linux-gnu/libcapnp-0.7.0.so
#6  0x0000555555a60b71 in capnp::writePackedMessage (output=..., builder=...)
    at /usr/include/capnp/serialize-packed.h:121
#7  0x0000555555a5c40c in rr::TraceWriter::write_mapped_region (this=0x555555c7d000, t=0x555555c7ea80, km=...,
    stat=..., file_name="", extra_fds=std::vector of length 0, capacity 0, origin=rr::TraceWriter::SYSCALL_MAPPING,
    skip_monitoring_mapped_fd=false) at ../src/TraceStream.cc:980
#8  0x000055555593efdf in rr::process_mmap (t=0x555555c7ea80, length=262144, prot=2, flags=50, fd=-1,
    offset_pages=0) at ../src/record_syscall.cc:5250
#9  0x0000555555956cd5 in rr::rec_process_syscall_arch<rr::X64Arch> (t=0x555555c7ea80, syscall_state=...)
    at ../src/record_syscall.cc:5805
#10 0x0000555555941e52 in rr::rec_process_syscall_internal (t=0x555555c7ea80, arch=rr::x86_64, syscall_state=...)
    at ../src/record_syscall.cc:6209
#11 0x0000555555941fd9 in rr::rec_process_syscall (t=0x555555c7ea80) at ../src/record_syscall.cc:6229
#12 0x0000555555921913 in rr::RecordSession::syscall_state_changed (this=0x555555c7cf10, t=0x555555c7ea80,
    step_state=0x7fffffffe06c) at ../src/RecordSession.cc:1175
#13 0x0000555555927426 in rr::RecordSession::record_step (this=0x555555c7cf10) at ../src/RecordSession.cc:2345
#14 0x00005555559191aa in rr::record (args=std::vector of length 1, capacity 1 = {...}, flags=...)
    at ../src/RecordCommand.cc:645
#15 0x0000555555919e33 in rr::RecordCommand::run (this=0x555555c64350 <rr::RecordCommand::singleton>,
    args=std::vector of length 1, capacity 1 = {...}) at ../src/RecordCommand.cc:787
#16 0x0000555555a9286b in main (argc=2, argv=0x7fffffffe468) at ../src/main.cc:268
```

After poking around capnp for a while, I realized the issue is that rr can somehow end up unmapping its own thread-local storage memory, and narrowed it down to the following reproducer: 

```
#include <stdlib.h>
#include <sys/mman.h>
int main(int argc, char **argv) {
mmap(0x70000000, 262144, PROT_WRITE, MAP_FIXED | MAP_ANONYMOUS | MAP_PRIVATE, -1, 0);
return 0;
}
```

Here's the part where rr unmaps itself:
```
#0  0x00007ffff7a3294b in munmap () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x000055555580a64a in rr::AddressSpace::<lambda(const rr::AddressSpace::Mapping&, const rr::MemoryRange&)>::operator()(const rr::AddressSpace::Mapping &, const rr::MemoryRange &) const (__closure=0x7fffffffc8e0, mm=..., rem=...)
    at ../src/AddressSpace.cc:1286
#2  0x000055555581155a in std::_Function_handler<void(const rr::AddressSpace::Mapping&, const rr::MemoryRange&), rr::AddressSpace::unmap_internal(rr::Task*, rr::remote_ptr<void>, ssize_t)::<lambda(const rr::AddressSpace::Mapping&, const rr::MemoryRange&)> >::_M_invoke(const std::_Any_data &, const rr::AddressSpace::Mapping &, const rr::MemoryRange &) (__functor=..., __args#0=..., __args#1=...) at /usr/include/c++/9/bits/std_function.h:300
#3  0x000055555581bf29 in std::function<void (rr::AddressSpace::Mapping const&, rr::MemoryRange const&)>::operator()(rr::AddressSpace::Mapping const&, rr::MemoryRange const&) const (this=0x7fffffffc8e0, __args#0=..., __args#1=...)
    at /usr/include/c++/9/bits/std_function.h:688
#4  0x000055555580f8dc in rr::AddressSpace::for_each_in_range(rr::remote_ptr<void>, long, std::function<void (rr::AddressSpace::Mapping const&, rr::MemoryRange const&)>, int) (this=0x555555c7c310, addr=..., num_bytes=262144, f=...,
    how=0) at ../src/AddressSpace.cc:1986
#5  0x000055555580a96a in rr::AddressSpace::unmap_internal (this=0x555555c7c310, addr=..., num_bytes=262144)
    at ../src/AddressSpace.cc:1292
#6  0x000055555580680c in rr::AddressSpace::map (this=0x555555c7c310, t=0x555555c7f0f0, addr=..., num_bytes=262144,
    prot=2, flags=19, offset_bytes=0, fsname="/dev/intel-fpga-port.0", device=6, inode=483,
    mapped_file_stat=std::unique_ptr<stat> = {...}, recorded_map=0x0,
    emu_file=std::shared_ptr<rr::EmuFile> (empty) = {...}, local_addr=0x0, monitored=...)
    at ../src/AddressSpace.cc:740
#7  0x000055555593f439 in rr::process_mmap (t=0x555555c7f0f0, length=262144, prot=2, flags=19, fd=3, offset_pages=0)
    at ../src/record_syscall.cc:5275
#8  0x0000555555956cd5 in rr::rec_process_syscall_arch<rr::X64Arch> (t=0x555555c7f0f0, syscall_state=...)
    at ../src/record_syscall.cc:5805
#9  0x0000555555941e52 in rr::rec_process_syscall_internal (t=0x555555c7f0f0, arch=rr::x86_64, syscall_state=...)
    at ../src/record_syscall.cc:6209
#10 0x0000555555941fd9 in rr::rec_process_syscall (t=0x555555c7f0f0) at ../src/record_syscall.cc:6229
#11 0x0000555555921913 in rr::RecordSession::syscall_state_changed (this=0x555555c7d4a0, t=0x555555c7f0f0,
    step_state=0x7fffffffd5ec) at ../src/RecordSession.cc:1175
#12 0x0000555555927426 in rr::RecordSession::record_step (this=0x555555c7d4a0) at ../src/RecordSession.cc:2345
#13 0x00005555559191aa in rr::record (args=std::vector of length 4, capacity 4 = {...}, flags=...)
    at ../src/RecordCommand.cc:645
#14 0x0000555555919e33 in rr::RecordCommand::run (this=0x555555c64350 <rr::RecordCommand::singleton>,
    args=std::vector of length 4, capacity 4 = {...}) at ../src/RecordCommand.cc:787
#15 0x0000555555a9286b in main (argc=5, argv=0x7fffffffd9e8) at ../src/main.cc:268
```

I'm not quite sure why this is happening, because that memory range doesn't seem occupied:
```
          Start Addr           End Addr       Size     Offset objfile
      0x555555554000     0x555555801000   0x2ad000        0x0 /usr/local/bin/rr
      0x555555801000     0x555555ad6000   0x2d5000   0x2ad000 /usr/local/bin/rr
      0x555555ad6000     0x555555c5e000   0x188000   0x582000 /usr/local/bin/rr
      0x555555c5e000     0x555555c63000     0x5000   0x709000 /usr/local/bin/rr
      0x555555c63000     0x555555c64000     0x1000   0x70e000 /usr/local/bin/rr
      0x555555c64000     0x555555ca4000    0x40000        0x0 [heap]
      0x7fffc0000000     0x7fffc0021000    0x21000        0x0
      0x7fffc0021000     0x7fffc4000000  0x3fdf000        0x0
      0x7fffc4000000     0x7fffc4021000    0x21000        0x0
      0x7fffc4021000     0x7fffc8000000  0x3fdf000        0x0
      0x7fffc8000000     0x7fffc8021000    0x21000        0x0
      0x7fffc8021000     0x7fffcc000000  0x3fdf000        0x0
      0x7fffcc000000     0x7fffcc021000    0x21000        0x0
      0x7fffcc021000     0x7fffd0000000  0x3fdf000        0x0
      0x7fffd0000000     0x7fffd0021000    0x21000        0x0
      0x7fffd0021000     0x7fffd4000000  0x3fdf000        0x0
      0x7fffd4000000     0x7fffd4021000    0x21000        0x0
      0x7fffd4021000     0x7fffd8000000  0x3fdf000        0x0
      0x7fffd8000000     0x7fffd8021000    0x21000        0x0
      0x7fffd8021000     0x7fffdc000000  0x3fdf000        0x0
      0x7fffdc000000     0x7fffdc021000    0x21000        0x0
      0x7fffdc021000     0x7fffe0000000  0x3fdf000        0x0
      0x7fffe0000000     0x7fffe0021000    0x21000        0x0
      0x7fffe0021000     0x7fffe4000000  0x3fdf000        0x0
      0x7fffe77ff000     0x7fffe7800000     0x1000        0x0
      0x7fffe7800000     0x7fffe8000000   0x800000        0x0
      0x7fffe8000000     0x7fffe8021000    0x21000        0x0
      0x7fffe8021000     0x7fffec000000  0x3fdf000        0x0
      0x7fffed15f000     0x7fffed7fb000   0x69c000        0x0
      0x7fffed7fb000     0x7fffed7fc000     0x1000        0x0
      0x7fffed7fc000     0x7fffedffc000   0x800000        0x0
      0x7fffedffc000     0x7fffedffd000     0x1000        0x0
      0x7fffedffd000     0x7fffee7fd000   0x800000        0x0
      0x7fffee7fd000     0x7fffee7fe000     0x1000        0x0
      0x7fffee7fe000     0x7fffeeffe000   0x800000        0x0
      0x7fffeeffe000     0x7fffeefff000     0x1000        0x0
      0x7fffeefff000     0x7fffef7ff000   0x800000        0x0
      0x7fffef7ff000     0x7fffef800000     0x1000        0x0
      0x7fffef800000     0x7ffff0000000   0x800000        0x0
      0x7ffff0000000     0x7ffff0021000    0x21000        0x0
      0x7ffff0021000     0x7ffff4000000  0x3fdf000        0x0
      0x7ffff405c000     0x7ffff42f2000   0x296000        0x0
      0x7ffff42f2000     0x7ffff42f3000     0x1000        0x0
      0x7ffff42f3000     0x7ffff4af3000   0x800000        0x0
      0x7ffff4af3000     0x7ffff4af4000     0x1000        0x0
      0x7ffff4af4000     0x7ffff52f4000   0x800000        0x0
      0x7ffff52f4000     0x7ffff52f5000     0x1000        0x0
      0x7ffff52f5000     0x7ffff5af5000   0x800000        0x0
      0x7ffff5af5000     0x7ffff5af6000     0x1000        0x0
      0x7ffff5af6000     0x7ffff6e11000  0x131b000        0x0
      0x7ffff6e11000     0x7ffff6e12000     0x1000        0x0
      0x7ffff6e12000     0x7ffff7917000   0xb05000        0x0
      0x7ffff7917000     0x7ffff793c000    0x25000        0x0 /usr/lib/x86_64-linux-gnu/libc-2.31.so
      0x7ffff793c000     0x7ffff7ab4000   0x178000    0x25000 /usr/lib/x86_64-linux-gnu/libc-2.31.so
      0x7ffff7ab4000     0x7ffff7afe000    0x4a000   0x19d000 /usr/lib/x86_64-linux-gnu/libc-2.31.so
      0x7ffff7afe000     0x7ffff7aff000     0x1000   0x1e7000 /usr/lib/x86_64-linux-gnu/libc-2.31.so
      0x7ffff7aff000     0x7ffff7b02000     0x3000   0x1e7000 /usr/lib/x86_64-linux-gnu/libc-2.31.so
      0x7ffff7b02000     0x7ffff7b05000     0x3000   0x1ea000 /usr/lib/x86_64-linux-gnu/libc-2.31.so
      0x7ffff7b05000     0x7ffff7b09000     0x4000        0x0
      0x7ffff7b09000     0x7ffff7b0c000     0x3000        0x0 /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
      0x7ffff7b0c000     0x7ffff7b1e000    0x12000     0x3000 /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
      0x7ffff7b1e000     0x7ffff7b22000     0x4000    0x15000 /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
      0x7ffff7b22000     0x7ffff7b23000     0x1000    0x18000 /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
      0x7ffff7b23000     0x7ffff7b24000     0x1000    0x19000 /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
      0x7ffff7b24000     0x7ffff7b26000     0x2000        0x0
      0x7ffff7b26000     0x7ffff7b35000     0xf000        0x0 /usr/lib/x86_64-linux-gnu/libm-2.31.so
      0x7ffff7b35000     0x7ffff7bdc000    0xa7000     0xf000 /usr/lib/x86_64-linux-gnu/libm-2.31.so
      0x7ffff7bdc000     0x7ffff7c73000    0x97000    0xb6000 /usr/lib/x86_64-linux-gnu/libm-2.31.so
      0x7ffff7c73000     0x7ffff7c74000     0x1000   0x14c000 /usr/lib/x86_64-linux-gnu/libm-2.31.so
      0x7ffff7c74000     0x7ffff7c75000     0x1000   0x14d000 /usr/lib/x86_64-linux-gnu/libm-2.31.so
      0x7ffff7c75000     0x7ffff7d0b000    0x96000        0x0 /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28
      0x7ffff7d0b000     0x7ffff7dfb000    0xf0000    0x96000 /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28
      0x7ffff7dfb000     0x7ffff7e44000    0x49000   0x186000 /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28
      0x7ffff7e44000     0x7ffff7e45000     0x1000   0x1cf000 /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28
      0x7ffff7e45000     0x7ffff7e50000     0xb000   0x1cf000 /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28
      0x7ffff7e50000     0x7ffff7e53000     0x3000   0x1da000 /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28
      0x7ffff7e53000     0x7ffff7e56000     0x3000        0x0
      0x7ffff7e56000     0x7ffff7e6f000    0x19000        0x0 /usr/lib/x86_64-linux-gnu/libkj-0.7.0.so
      0x7ffff7e6f000     0x7ffff7ec1000    0x52000    0x19000 /usr/lib/x86_64-linux-gnu/libkj-0.7.0.so
      0x7ffff7ec1000     0x7ffff7edb000    0x1a000    0x6b000 /usr/lib/x86_64-linux-gnu/libkj-0.7.0.so
      0x7ffff7edb000     0x7ffff7edc000     0x1000    0x85000 /usr/lib/x86_64-linux-gnu/libkj-0.7.0.so
      0x7ffff7edc000     0x7ffff7edf000     0x3000    0x85000 /usr/lib/x86_64-linux-gnu/libkj-0.7.0.so
      0x7ffff7edf000     0x7ffff7ee0000     0x1000    0x88000 /usr/lib/x86_64-linux-gnu/libkj-0.7.0.so
      0x7ffff7ee0000     0x7ffff7ee7000     0x7000        0x0 /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
      0x7ffff7ee7000     0x7ffff7ef8000    0x11000     0x7000 /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
      0x7ffff7ef8000     0x7ffff7efd000     0x5000    0x18000 /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
      0x7ffff7efd000     0x7ffff7efe000     0x1000    0x1c000 /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
      0x7ffff7efe000     0x7ffff7eff000     0x1000    0x1d000 /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
      0x7ffff7eff000     0x7ffff7f03000     0x4000        0x0
      0x7ffff7f03000     0x7ffff7f26000    0x23000        0x0 /usr/lib/x86_64-linux-gnu/libcapnp-0.7.0.so
      0x7ffff7f26000     0x7ffff7f7f000    0x59000    0x23000 /usr/lib/x86_64-linux-gnu/libcapnp-0.7.0.so
      0x7ffff7f7f000     0x7ffff7fa0000    0x21000    0x7c000 /usr/lib/x86_64-linux-gnu/libcapnp-0.7.0.so
      0x7ffff7fa0000     0x7ffff7fa1000     0x1000    0x9d000 /usr/lib/x86_64-linux-gnu/libcapnp-0.7.0.so
      0x7ffff7fa1000     0x7ffff7fa4000     0x3000    0x9d000 /usr/lib/x86_64-linux-gnu/libcapnp-0.7.0.so
      0x7ffff7fa4000     0x7ffff7fa5000     0x1000    0xa0000 /usr/lib/x86_64-linux-gnu/libcapnp-0.7.0.so
      0x7ffff7fa5000     0x7ffff7fa6000     0x1000        0x0 /usr/lib/x86_64-linux-gnu/libdl-2.31.so
      0x7ffff7fa6000     0x7ffff7fa8000     0x2000     0x1000 /usr/lib/x86_64-linux-gnu/libdl-2.31.so
      0x7ffff7fa8000     0x7ffff7fa9000     0x1000     0x3000 /usr/lib/x86_64-linux-gnu/libdl-2.31.so
      0x7ffff7fa9000     0x7ffff7faa000     0x1000     0x3000 /usr/lib/x86_64-linux-gnu/libdl-2.31.so
      0x7ffff7faa000     0x7ffff7fab000     0x1000     0x4000 /usr/lib/x86_64-linux-gnu/libdl-2.31.so
      0x7ffff7fab000     0x7ffff7fad000     0x2000        0x0
      0x7ffff7fcb000     0x7ffff7fce000     0x3000        0x0 [vvar]
      0x7ffff7fce000     0x7ffff7fcf000     0x1000        0x0 [vdso]
      0x7ffff7fcf000     0x7ffff7fd0000     0x1000        0x0 /usr/lib/x86_64-linux-gnu/ld-2.31.so
      0x7ffff7fd0000     0x7ffff7ff3000    0x23000     0x1000 /usr/lib/x86_64-linux-gnu/ld-2.31.so
      0x7ffff7ff3000     0x7ffff7ffb000     0x8000    0x24000 /usr/lib/x86_64-linux-gnu/ld-2.31.so
      0x7ffff7ffb000     0x7ffff7ffc000     0x1000        0x0 /tmp/rr-shared-preload_thread_locals-190988-0 (deleted)
      0x7ffff7ffc000     0x7ffff7ffd000     0x1000    0x2c000 /usr/lib/x86_64-linux-gnu/ld-2.31.so
      0x7ffff7ffd000     0x7ffff7ffe000     0x1000    0x2d000 /usr/lib/x86_64-linux-gnu/ld-2.31.so
      0x7ffff7ffe000     0x7ffff7fff000     0x1000        0x0
      0x7ffffffdd000     0x7ffffffff000    0x22000        0x0 [stack]
  0xffffffffff600000 0xffffffffff601000     0x1000        0x0 [vsyscall]
```

**Comment by khuey** [comment]
The issue that was making us go off the rails unmapping things is fixed. Unmapping the rr page still isn't actually supported though, so the tracee will likely fail elsewhere.

**Comment by ddcc** [comment]
Oh, this is conflicting with the rr page in the tracee, and not the actual mappings of the tracer

**Comment by khuey** [comment]
Yes, but the mmap you're doing is longer than the page that's shared between rr and the tracer, and we weren't previously bounding the length of the munmap we do to get rid of the shared page to the length of that page, so we were munmaping random stuff from the tracer address space.

**Comment by ddcc** [comment]
Makes sense now, thanks for the explanation!
